### ISSUE TITLE
Retweet feature

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#10]
Since Twitter implements a retweet feature, Chromed Bird do not work with

**Comment by cezarsa** [comment]
I'm really not sure yet if it worths implementing this feature. The main problem is that a great deal of people like to edit their RT's adding personal comments on the tweet. Twitter's new retweet feature doesn't allow that, you simply forward the tweet with no edits.
Maybe I could support both kinds of retweets but I don't wanna make users confused by that.

**Comment by ghost** [comment]
Currently, there are two link : Reply and RT
Maybe you can add a third, then link will work the following :
Reply : No change, same as currently
RT : Simple RT without personal comment
Share : RT with personal comment

**Comment by cezarsa** [comment]
Ability to use Twitter's new retweet API. Closed by 8692d533ec90c81723bbc784c8cc047978508a16
