### ISSUE TITLE
Linkify urls starting with www

### ISSUE THREAD

**Issue by xavivars** [cezarsa/silver_bird#100]
Currently, links are created automatically when a url starting with http(s), ftp or file, followed by ://

It would be a good idea to add into "transformList" array the following code snippet
(inside `transformTweetText`, at twitter_assembler.js line 44)

```
{
    //create links
    'expression': /(\bwww\.[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,
    'replacement': "<a href='$1'>$1</a>"
},
```

or, much better, merge it with the current one

```
{
    //create links
    'expression': /(\b(((https?|ftp|file):\/\/)|www\.)[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,
    'replacement': "<a href='$1'>$1</a>"
},
```

**Comment by cezarsa** [comment]
Linkifying urls starting with www. Closed by a8214137a5e84870cf94a8339c9bbf20f157f6cb

**Comment by cezarsa** [comment]
Thanks xavivars! I've just pushed this change.

**Comment by xavivars** [comment]
It seems it's not working now. An upgrade broke this patch.
