### ISSUE TITLE
Create Search Tabs

### ISSUE THREAD

**Issue by elijahmanor** [cezarsa/silver_bird#101]
Just like you can have one or more Twitter List tabs, I would like to create one ore more Twitter Search tabs.

**Comment by cezarsa** [comment]
That's something already on my roadmap. It's one of the new features I plan for the next major version.

**Comment by Hirsute** [comment]
Wonderful.  It's the only thing I really miss from my other Twitter access methods.  Wonderful extension.

**Comment by cezarsa** [comment]
We now have search tabs! The main commit was 1be05a3c769b9576296057ab6a61a6e932090ae6
Closing this issue.
