### ISSUE TITLE
OAuth an account again

### ISSUE THREAD

**Issue by thetitan** [cezarsa/silver_bird#102]
How do I get Chrome Bird to OAuth with my Twitter account again?

I keep getting the date/time/zone warning message. Bu my system's time has been correct since the systems was build 3 years ago! The problem is that when I go to the options page the OAuth information, like the token, is missing. There isn't a button to Authenticate an account and attempting to do it in other ways, like clicking on the bird, I receive the "time" message.

I'm using Chromed Bird - Version: 1.6.1.

**Comment by cezarsa** [comment]
I admit, OAuth is a pain. This might be related to your daylight saving time settings or maybe Chrome is getting timezone configurations from some unusual place.
But I just had an idea that might save us from this struggle and keep OAuth working even with completely messed up clocks.
I've just pushed commit 45e800902dd22d8ee022fcbd71dbd373b878f9d8 and it tries to compensate your clock settings based on the timestamp returned by Twitter itself.
It would be really nice if you could try installing current source as an unpacked extension to see if it solves the problem. You can download it here: http://github.com/cezarsa/chromed_bird/zipball/master

Just a side note: The OAuth Authorize URL setting in the options page should be left the way it is.

**Comment by thetitan** [comment]
I got Chrome Bird to work. You were right, it was a time issue. The problem was not with the operating system's time, but with the hardware time. Recently the system crashed during boot and it messed up the BIOS. The date in the BIOS was off by one day!

It works fine now. Thank you for your fast response.

**Comment by cezarsa** [comment]
Cool, good to hear it's working now. Closing this issue.
