### ISSUE TITLE
Hyphenation for long links/letter sequences

### ISSUE THREAD

**Issue by vanushah** [cezarsa/silver_bird#104]
I don't like when my Chromed Bird blows up in width every time someone posts a long link (without shortening it) or uses a lot of letters in one single word without spaces.

Let illustrate my words:

http://imgur.com/FHEdT.png

**Comment by cezarsa** [comment]
Hey there, so I'm working on popup window resizing and also fixing this up. Hang on for the next release.

**Comment by vanushah** [comment]
Thanks.

**Comment by cezarsa** [comment]
Allowing dynamic popup window resizing. Also closed by a50a88fb664b0452327e1ff25c23feae9bfbef23
