### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by antonini** [cezarsa/silver_bird#105]
I've changed URLS of the configuration to use SSL (HTTPS), just changed to HTTPS, and the plugin is not working.
This extension just works using HTTP?

**Comment by cezarsa** [comment]
Hi antonini, it should work with HTTPS as well. Did you also update the "OAuth Signature URL" in the options page? You probably need to make it equal to "Twitter's API URL" setting.

**Comment by antonini** [comment]
Hi cezarsa!
I've changed this options to:
Twitter's API URL: https://twitter.com/
https://twitter.com/: https://twitter.com/
OAuth Authorize URL: https://twitter.com/oauth/authorize?oauth_token=

Is it correct?

**Comment by cezarsa** [comment]
Yeah, that should work. Is it still not working after disabling and enabling the extension?
I can't test it right now but I'll give it a try as soon as I get home.

**Comment by antonini** [comment]
No, It didn't worked!

Error: Unexpected error "undefined"(parsererror) fetching lists. Try again.

I know that I have a "special" situation, I'm behind proxy, and the proxy reject's any HTTP connection to twitter.com.
But the proxy allows to use HTTPS with twitter...

If I access twitter (through Browser) using this https://twitter.com/ it works on my browser.

Is possible that internaly the extension is trying to access twitter.com through HTTP?

**Comment by cezarsa** [comment]
Probably not, it should only access Twitter through configured URLs. I'll test it as soon as I get home.

**Comment by JohanKlos** [comment]
These work for me:
Twitter's API URL: https://api.twitter.com/1/
OAuth URL: https://twitter.com/oauth/

**Comment by cezarsa** [comment]
Yeah, HTTPS API endpoints have been the default options for a while now. I really need to clean up some old issues ;)
