### ISSUE TITLE
Long twit words

### ISSUE THREAD

**Issue by dzsodzso63** [cezarsa/silver_bird#106]
If somebody twits a longlonglong word (ie "aaaaaaa...." http://twitter.com/sillybunny_bp/status/9972828471 ), the chromed_bird window appear very wide, end left side with avatars cuts off at the left of the screen.

**Comment by cezarsa** [comment]
Hey there, thanks for reporting.
This issue have been fixed by commit a50a88fb664b0452327e1ff25c23feae9bfbef23. Hang on for the next release.
