### ISSUE TITLE
"New Tweet" bar not updating after tweeting

### ISSUE THREAD

**Issue by sycobuny** [cezarsa/silver_bird#107]
The bar displaying the message similar to "X more tweets available. Click here to update now." does not correctly update after posting a tweet. The timeline is automatically refreshed, but the bar doesn't go away until clicked. After receiving more undisplayed tweets, the number adjusts to the correct count.

**Comment by cezarsa** [comment]
Fixing timeline update after sending a tweet. Closed by ce35c520c0715eed47d6b08173ff0839c7ff86e9
Also improved consistency replying to DMs.
