### ISSUE TITLE
Share this page

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#11]
It will be great if there's a functionality which allows us to share the current page, and shortens long url
Maybe also a direct link to twitter website.

**Comment by cezarsa** [comment]
Lots of people are requesting integration with url shortening services. That's definitely going to be present on the next version. Thanks for reporting it so I won't forget. :)

**Comment by cezarsa** [comment]
URL shortening completed, also some improvements in keyboard navigation. closed by 9fcfbbdcc5e126c2d74a2a56539fb46d332aa6ad and closed by 9fcfbbdcc5e126c2d74a2a56539fb46d332aa6ad
