### ISSUE TITLE
ChromedBird has no Acces to Twitter (Connections)

### ISSUE THREAD

**Issue by JBantha** [cezarsa/silver_bird#111]
So! ^^ how you doing? ^^
I'm fine, except for the fact that ChromedBird isn't working like... 3 months ago. I've been using Metrist but, at least for me, it's just not as good as ChromedBird.
Finally I decide to see what was te problem, and I realize that ChromedBird does not have the corresponding Twitter Access (Settings/conecctions) and in the many time I have try to "fix it" (i don't know too much about APIs as you can see)    it have NEVER ask me for TwitterAccess, excepting the very first time.
So, how can I give it the rigth permission?

Help me "cezarsa"... you are my only hope!

**Comment by cezarsa** [comment]
Hey there, so, let me see if I understand you correctly. Chromed Bird is not showing in Twitter's connections page, and it does not ask you for permission, right?
First thing to try is clicking Chromed Bird's icon and then clicking the "Log out" link in the top left corner. After that, the next time you click Chromed Bird's icon it should open Twitter's OAuth authorization page. Does this solve your problem?

**Comment by spitfire2** [comment]
I think JBantha need a proxy like tor (or other proxy software) to  get OAuth token.

**Comment by JBantha** [comment]
(PLZ excuse my english)
okay, cezarsa get my issue right, but  when I click the Bird what it comes out is this:
http://i124.photobucket.com/albums/p17/JBantha/sale.jpg
