### ISSUE TITLE
Closed notification

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#112]
When I close a desktop notification, the twit is still on unread.
Well, when I close a desktop notification, it's because I read it.
Maybe a configurable parameter ?

**Comment by cezarsa** [comment]
Yeah, you're right, that should probably be quite easy to do with desktop notifications contrary to on page notifications. I'll make sure to try this on the next version.

**Comment by cezarsa** [comment]
Forgot to close on commit message, so closing now. Commit: db8fdee7aa1fa5c5a5609eff649ca5bc73ed346e
