### ISSUE TITLE
Error message regarding blocked users

### ISSUE THREAD

**Issue by Ikke** [cezarsa/silver_bird#113]
I regularly get an error message in chromed bird:

> Could not retrieve your list of blocked users. Will auto retry later

I have the latest version on the master branch.

**Comment by cezarsa** [comment]
You're living on the edge, dude! :) I've done some extensive refactoring the last few days, and some stuff (mainly lists) aren't a hundred percent correct yet, there may be something wrong with blocked users retrieval too.
Anyway, I think this warning message is largely unnecessary. Even if there's a failure loading blocked users list I don't think we should bother warning users, it'd be better to silently try again some time latter. I'll take a look at this. Thanks for reporting!
