### ISSUE TITLE
Add Option to Not Include Search Tweet Count in Overall Browser Action Count

### ISSUE THREAD

**Issue by elijahmanor** [cezarsa/silver_bird#114]
I pulled down the latest from your GitHub and imported it into Google Chrome because I saw you added search tabs. I really like what you have done there, but would like the option to opt out of the seach tweets from being added to the browser action overall count. As it is now, the icon is showing 809 new tweets that I don't necessary want to see them all :) It kind of drowns out my other more important tweets (mentions, DMs, etc...) http://gyazo.com/584086f43f4c7d4cd04f17a33defccf9.png

**Comment by cezarsa** [comment]
Hey Elijah, you should be able to turn off "Change Icon" notifications for search tabs in the options page. Actually, that's a bit odd because the default setting was supposed to have them turned off. Haven't you enabled it?

**Comment by cezarsa** [comment]
Not showing new tweets count for timelines without icon notifications. Closed by 9c1a2c6e9b8df478b660a2efbae6fda8974a0509
