### ISSUE TITLE
Follow/Unfollow Suggestions & Have a Block Feature

### ISSUE THREAD

**Issue by elijahmanor** [cezarsa/silver_bird#115]
In addtion to the follow/unfollow feature you mentioned in your roadmap I think a block feature would fit nicely w/ those as well. 

W/ the follow/unfollow I'd really like it smart enough to know if I already follow the person (example: only show unfollow option if I follow them, only show follow option if I don't follow them).

**Comment by cezarsa** [comment]
Adding block and report span actions. Closed by 29be16a3e7848af4e2e533996aa9d8c8ecd6f930.
