### ISSUE TITLE
Missing all my Chrome Bird buttons

### ISSUE THREAD

**Issue by Jeffhoard** [cezarsa/silver_bird#116]
I have lost all my "Retweet" and "Reply" related buttons within Chromebird?

In the past when I hovered over a tweet, some buttons would appear in the right hand side of the box with buttons that included "old school re-tweet" - They don't appear anymore?

This all started when I used the drag function to make my Chromebird window appear larger, now I can't shrink the window. 

I have tried uninstalling the application to "reset" it - however when I re-install it, it appears as it did previously - I'd really like to just "start fresh" as if I had never used it before to solve the problem.

Any ideas on how I can get these fixed, I really liked chrome bird, I even gave up Twhirl because of it, but now this this small issue has had me looking for new alternatives.

**Comment by cezarsa** [comment]
Just go to the options page and click the "Reset Popup Size" in the UI area. Another option is to simply double-click the resize handle in the popup.

**Comment by Jeffhoard** [comment]
Beauty, thanks that worked
