### ISSUE TITLE
Chinese characters not displaying

### ISSUE THREAD

**Issue by Jeffrey04** [cezarsa/silver_bird#12]
Just got updated in the afternoon to version 0.5, however, I just discovered that chinese characters are not being displayed in the time line (do not have friend that uses other asian characters though)

**Comment by cezarsa** [comment]
That's odd, I didn't change anything in the way characters are rendered. Did it work before the 0.5 update?

**Comment by Jeffrey04** [comment]
Yea, it worked before the update :D i like the new update (mainly because of oauth) XD

**Comment by Jeffrey04** [comment]
I tried opening popup.html as shown here: http://code.google.com/chrome/extensions/tut_debugging.html

console.log returns chinese text properly but it somehow doesn't get posted to the page properly (also compared to the code in 0.4 and found no much difference) :/

**Comment by Jeffrey04** [comment]
look like this is chrome's problem

http://groups.google.com/group/chromium-extensions/browse_thread/thread/85a69eb1ae5eefbf#

http://code.google.com/p/chromium/issues/detail?id=28771

**Comment by cezarsa** [comment]
Yeah, that seems to be the case indeed. However I don't think that this issue is happening with everyone. I tested following some Chinese and Japanese people on Twitter and the characters were shown correctly.
I'll leave this issue open for further investigation. Thanks for reporting.

**Comment by Jeffrey04** [comment]
should have included this in the beginning

tested on chrome version 4.0.249.11 and 4.0.257.0 (Ubuntu build 33067)

**Comment by Jeffrey04** [comment]
issue solved with 4.0.266.0 :D

**Comment by cezarsa** [comment]
Really nice, thanks for checking it out Jeffrey. I'll close this issue now.
