### ISSUE TITLE
Resizing the window makes the scrollbars resize incorrectly

### ISSUE THREAD

**Issue by x-cubed** [cezarsa/silver_bird#122]
I made the main Chromed Bird dropdown window a little taller by dragging the bottom edge down, but now I don't have a scroll bar on the Unified tab anymore, and the scroll bar on the Home tab has its bottom thumb button hidden below the bottom of the window. The window can now no longer be resized (presumably the resize thumb is off the bottom of the window too) so I'm stuck with no scroll bar at the moment.

**Comment by cezarsa** [comment]
It's hard to predict how large Chrome will allow the popup to grow, that's why it grows indefinitely.
To fix this problem you can go to the options page and click the "Reset Popup Size" button in the UI frame.
