### ISSUE TITLE
Middle click on links closes the Chromed Bird frame

### ISSUE THREAD

**Issue by MalabarFront** [cezarsa/silver_bird#125]
As per the title, middle-clicking links in Tweets now closes the Chromed Bird frame instead of the old behaviour of silently opening the link in a new tab in the background.

I frequently perform this action to open tabs for later while I'm catching up on tweets. Having the frame close, forcing me to re-open it and find my place, is fairly jarring.

Is this a bug? Thanks.

**Comment by spitfire2** [comment]
+1

**Comment by cezarsa** [comment]
Fixing opening links in the background when middle-clicking. Closed by 77ddc0c96adb254973a94c78f5fddf3872c67ee5
