### ISSUE TITLE
Scrollbar disappeared

### ISSUE THREAD

**Issue by Feroc** [cezarsa/silver_bird#126]
I just started chrome this morning and checked twitter. I noticed, that I don't have a scrollbar anymore:

http://tinyurl.com/32bpw3k

I can still scroll if I select some text with my mouse and move it down:

http://tinyurl.com/2vxnj4h

Tried to restart chrome and to reinstall Chromed Bird, but it doesn't fix it.

**Comment by cezarsa** [comment]
Could you try going to the options page and clicking the "Reset Popup Size" button in the UI area?

**Comment by miralie** [comment]
Just so you know, I was having the exact same problem and "Reset Popup Size" worked for me.

**Comment by mysterious1der** [comment]
Just popping in to say I had the same problem (No scrollbars on the Unified tab in Chrome on OSX 10.6, but I had scrollbars on other tabs) and "Reset Popup Size" helped me as well. Thanks all!

**Comment by cezarsa** [comment]
As of 1.9.5.1 it shouldn't be possible to expand the popup until the scrollbars disappear anymore.
