### ISSUE TITLE
Re-version

### ISSUE THREAD

**Issue by yelvington** [cezarsa/silver_bird#13]
The released version at http://cezarsa.github.com/chromed_bird/ claims 0.5, and I successfully installed 0.5 on my work laptop just fine. I drove home and I can now get only 0.4, unless I pull the unpacked version out of Git. Whaaaa?

0.5 is looking good. Now, it just needs URL shortening and decoding... :-)

**Comment by yelvington** [comment]
Looking at the html:

http://cloud.github.com/downloads/cezarsa/chromed_bird/chromed_bird_0.4.crx is on the release page

http://cloud.github.com/downloads/cezarsa/chromed_bird/chromed_bird_0.5.crx is in the version of the release page committed to Git.

Shift-reload forces Chrome to clear its cache

Now I see http://cloud.github.com/downloads/cezarsa/chromed_bird/chromed_bird_0.5.crx

So it apparently was the Chrome browser caching the launch page. Arggh!

**Comment by cezarsa** [comment]
Good call. Caching issues are a bitch. :)
I'm closing this issue and gonna add meta tags to avoid further caching of the download page. Thanks!
