### ISSUE TITLE
Improve URL Handling

### ISSUE THREAD

**Issue by Roguelazer** [cezarsa/silver_bird#130]
The current URL recognition regular expression is a bit weak. I copied in John Gruber's from http://daringfireball.net/2009/11/liberal_regex_for_matching_urls to Roguelazer/chromed_bird@1a58b8d7c150dd0e613d if you're interested in merging in.

**Comment by Roguelazer** [comment]
Which is to say, Roguelazer/chromed_bird@1a58b8d7c150dd0e613d196d7da4360daca811a3 possibly. The lack of preview for GitHub comments is kind of annoying.

**Comment by cezarsa** [comment]
Thanks a lot, this URL regexp is much better indeed. Your changes have already been merged.
