### ISSUE TITLE
#hashtag at start of tweet is not hyperlinked

### ISSUE THREAD

**Issue by moreati** [cezarsa/silver_bird#131]
A #hashtag at the first character of a tweet is not made into a hyperlink, like those in other positions.
Chromed Bird 1.8.0 on Ubuntu 10.04, Chromium 5.0.396.0 (46318)

**Comment by cezarsa** [comment]
It's been already fixed on master branch: e9d9b298546667ed5c037c973beeb33d09074418 I'll soon make a bug fix release, I promise. :)

**Comment by moreati** [comment]
I wondered why the code I was looking at looked fine :) Thank you
