### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#14]
It seems that autoupdate doesn't work.
On chrome starter guide, it's told that version number must not start with 0

**Comment by cezarsa** [comment]
I just tested it now, and it appears to be working fine, maybe it was just a network glitch or some caching issues. Did you try clicking "Update extensions now"?

According to http://code.google.com/chrome/extensions/manifest.html#version : "they must be between 0 and 65535, inclusive, and non-zero integers can't start with 0."
So, I understand that it's okay to have 0.1 but it wouldn't be okay to have 01.1

**Comment by ghost** [comment]
I don't really know, I never succed in updating your extension via "Update extension now" button...

**Comment by cezarsa** [comment]
I just installed version 0.4 (available in the downloads tab) and clicked update extension now, and it updated it to 0.51. Could you try it there?

**Comment by spitfire2** [comment]
I also have the same problem.

**Comment by spitfire2** [comment]
I can update it now.

**Comment by cezarsa** [comment]
Nice, I have switched the auto update URL to use Google's official extension gallery. It should be more reliable now. I'm closing this issue.
