### ISSUE TITLE
disable/customize fade animation for notifications

### ISSUE THREAD

**Issue by nikil** [cezarsa/silver_bird#140]
It would be great if we could either disable the slow fade-out animation for tweet notifications or at least customize how quickly it fades out.  To me, it seems notifications are fading out really slowly, and for half of that fade time the notification is too transparent to even read.  Thanks for the great extension!

**Comment by cezarsa** [comment]
Hi, you can already customize the fade out time for on page notifications in the options page, just change the "Notification Timeout" field.
Another option is to switch to Desktop Notifications, they look much better and they will be the default notification style in the next version.
