### ISSUE TITLE
Maintain Timeline Scroll Position

### ISSUE THREAD

**Issue by jk0** [cezarsa/silver_bird#142]
Title says it all.

**Comment by cezarsa** [comment]
It already maintains the scroll position for each individual timeline. Is there any context in which this isn't working? I couldn't reproduce this myself.

**Comment by jk0** [comment]
It's not maintaining the position in any of the timelines for me. It's always positioned at the very top, so I have to scroll down to read all of the new tweets.

Is there a setting somewhere that I am missing?

**Comment by ddlevine** [comment]
For me, the timeline maintains its position while Chrome is open. However, if I close and reopen Chrome, the timeline starts back at the top.

Would it be possible to maintain the timeline position even when Chrome is closed and reopen?

**Comment by jk0** [comment]
^ That's exactly what I'm experiencing as well. Quite frustrating.

**Comment by ddlevine** [comment]
I'm not sure what happened, but I just realized that the scroll position is not saved, even during the current session. I am using Chrome 6.0.495.0 dev.

**Comment by ddlevine** [comment]
I guess it was just something weird going on because everything is working fine and Chromed Bird wasn't updated.
