### ISSUE TITLE
URL shortening

### ISSUE THREAD

**Issue by jacarui** [cezarsa/silver_bird#15]
Like many twitter apps, just write an URL and when accepted, automaticaly recognize URLs and short them with bitly or one of these:
http://www.toprankblog.com/2009/01/11-best-url-shortening-services-vote-your-favorite/

**Comment by cezarsa** [comment]
Yeah, this one is the first in my list of priorities for Chromed Bird. Wait until the weekend. :)

**Comment by cezarsa** [comment]
URL shortening completed, also some improvements in keyboard navigation. closed by 9fcfbbdcc5e126c2d74a2a56539fb46d332aa6ad and closed by 9fcfbbdcc5e126c2d74a2a56539fb46d332aa6ad
