### ISSUE TITLE
YOURLS personal URL shortener support

### ISSUE THREAD

**Issue by packetcollision** [cezarsa/silver_bird#167]
First of all, thanks for making this great Chrome extension.  After a few scares with url shorteners (nearly) shutting down, some of us have decided to run our own personal shortener service, using the open-souce [YOURLS](http://yourls.org/) package.  Support for it in Chromed Bird would be great.  The API is pretty simple, simply send a GET or POST to http://yoursite.com/yourls-api.php with the following parameters (documented further [here](http://yourls.org/#API)):
action=shorturl
url=_http://the.url.you.want.to/shorten_
format=simple
and either:
signature=_API signature token_
or:
username=_username_
password=_password_

I'll see if I can hack this together myself, but I've never looked at Chrome extension internals before, so I thought I should go ahead and write a feature request anyway.

**Comment by packetcollision** [comment]
Steward Allen has already created a version with YOURLS support.  I haven't figured out how to build Chrome extensions yet, but I assume his branch works.  Perhaps you could pull in his changes and make sure they work? http://github.com/stewartallen/chromed_bird/commit/b8d8bc3bf33b8a30f2bc4ef12b3cfd7983508f55

**Comment by stewartallen** [comment]
Hey guys,

You can get chrome to load unpackaged extensions. Go to the extensions page, expand the "Developer mode" tab thing and then click on the "Open unpacked extention". Just point it to the folder where the chrome bird source is.

BTW I've been using my YOURLS patch for a couple months now and it seems to run perfectly.  I've put in a merge request but haven't heard back. 

Last thing, my patch is up to date with the latest "master" from cezarsa / chromed_bird

**Comment by packetcollision** [comment]
I can confirm that the branch works as expected.  I'd love to see this merged with upstream.
