### ISSUE TITLE
Notification icon for number of unread tweets is hard to read

### ISSUE THREAD

**Issue by moskie** [cezarsa/silver_bird#172]
With a recent update to Chrome, the red block icon showing the number of unread tweets has become distorted and hard to read. It is still partially legible, but in the past it was much clearer.

Here's a link to an example screenshot: http://i.imgur.com/GBUoU.png

Reported in Chrome Dev Channel version 6.0.490.1.

**Comment by moskie** [comment]
In case it's useful, here's screenshots of it with two and four tweets unread, which I think better shows that it's hard to read. http://i.imgur.com/DYoNs.png

**Comment by ddlevine** [comment]
This was a bug with all extensions in that version of Chrome which has since been fixed.

**Comment by cezarsa** [comment]
Thanks for checking MooPenquin. That's what I thought as there's no API call to change the badge text font.
