### ISSUE TITLE
Middle-click to open in new tab is broken in dev channel

### ISSUE THREAD

**Issue by tbroyer** [cezarsa/silver_bird#187]
In "7.0.517.8 dev" (and at least one previous version), middle-clicking a link no longer opens it in a new tab (it just does nothing, like a right-click). You're forced to lef-click on a link to open it, but then it doesn't open in background.

**Comment by duanemck** [comment]
I am experiencing the same issue with Chrome 7.0.517.24 beta on Ubuntu 10.04

**Comment by martiner** [comment]
The same on 7.0.517.24 beta on Vista and Ubuntu Karmic.
Ctrl+left click works, though.

**Comment by cezarsa** [comment]
Sorry for that guys, I broke it while trying to make it work on xp... Also some newer Chrome versions apparently stopped raising onclick events for the middle button.... A fix is coming shortly, hang on.

**Comment by cezarsa** [comment]
Hey guys, I've just pushed a possible fix (f2e556aacea0ee08b6627341bc84b48451a4a5ff). Would you mind testing the current source on your platforms?
To test it you can simply download the source [1] and select "load unpacked extension..." in the extensions page.

**Comment by cezarsa** [comment]
[1] - http://github.com/cezarsa/chromed_bird/zipball/master

**Comment by duanemck** [comment]
Just tested on Chrome 7.0.517.24 beta on Ubuntu 10.04 and it seems to be working. Although, only if Chrome is the only window visible (everything else is minimized). If not, Chrome seems to lose focus and disappear behind the window behind it, but when I refocus it, the link has opened in another tab. This may be a Chrome issue though, not sure.

**Comment by duanemck** [comment]
Oh, and thanks for the quick response, awesome support for an awesome extension. Keep up the good work.

**Comment by tbroyer** [comment]
ChromedBird 1.9.1 on Chrome 7.0.544.0 dev works OK for me (tested both at work on WindowsXP and at home on Vista).

Thanks Cezar!
