### ISSUE TITLE
"Compose" beneath the tweets

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#19]
Move the "compose tweet" form to the bottom of the popup.

**Comment by xflx** [comment]
I like it where it is

**Comment by cezarsa** [comment]
I plan in offering this as a config in the options page. The default one would be in the same place where it's today.

**Comment by cezarsa** [comment]
Allowing user to change the position of Compose area. Closed by 5f25661e9060c1e5471bdfae1b67fa5b27f04ac0
