### ISSUE TITLE
Desktop Notifications - choice of monitor display

### ISSUE THREAD

**Issue by chuckstar76** [cezarsa/silver_bird#200]
I like the desktop notification feature - however, I have no control on the positioning of the notifcation relative to the window or which monitor it appears on.  Is this something you can help with?  I'm using Windows 7 with two monitors (1 primary and 2 extended desktop). Currently Chromed bird notifications appear at the bottom right of primary monitor (not noticed) - others (Digsby) appear bottom left of extended monitor (more useful).

**Comment by cezarsa** [comment]
The problem with desktop notifications is that I have absolutely no control over how they appear. The specification itself [1] only includes one non-normative section saying that it's up to the browser to find the best way of displaying them.
Browsing through Chromium bug-tracker I found some issues related to this problem, you might want to star some of these issues:
http://code.google.com/p/chromium/issues/detail?id=42313
http://code.google.com/p/chromium/issues/detail?id=32369
http://code.google.com/p/chromium/issues/detail?id=41883 (I think this approach is the one I prefer)

[1] http://dev.w3.org/2006/webapi/WebNotifications/publish/

**Comment by cezarsa** [comment]
Closing as there's nothing I can do right now.

**Comment by chuckstar76** [comment]
Hi, thanks for looking into this.
