### ISSUE TITLE
unable to install Chromed Bird on Linux box running Ubuntu

### ISSUE THREAD

**Issue by talischris** [cezarsa/silver_bird#205]
Here's the message I get:

/tmp/com.google.chrome.208Geu/TEMP_INSTALL/_locales/de_DE/messages.json: Unsupported encoding. JSON must be UTF-8.

**Comment by cezarsa** [comment]
Ouch, that's bad, sorry for that, I should've checked before. It's been fixed by cb0b80cc25eb0a0361d81c3bc88947135cf5e857
