### ISSUE TITLE
Customize icon

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#21]
Add an option to change the browseraction icon, to get an chromifed one

**Comment by cezarsa** [comment]
Allowing users to dynamically 'upload' new icons is a tough one. I don't think it's really possible. One alternative though is to have multiple icons and letting the user choose one of them in the options page. Do you have any icon set in mind?
Also I plan in dynamically 'paint' the icons using canvas, so it wouldn't be necessary to include blue and red icons in the extension.

**Comment by ghost** [comment]
I think it's possible to upload browser action for users using npapi but it's not what I want you to do ! ^_^"
Actually, it's a option (like in gmail checker and google reader checker by destrubot or google tasks by me) to chosse between two (or more) sets of icons

**Comment by cezarsa** [comment]
Customizing icon notifications. Closed by 51267be653aa8eba93f00323ecef605fdc2c2033 and Closed by 51267be653aa8eba93f00323ecef605fdc2c2033
