### ISSUE TITLE
Tweets aren't wrapping properly

### ISSUE THREAD

**Issue by speener** [cezarsa/silver_bird#214]
Since the most recent update - my tweets aren't wrapping properly - the buttons to reply, retweet, etc. are forced off screen. If you drag the cursor to the right - the buttons do appear.

I have reset the pop-up window - that does nothing. I can send a screenshot if you'd like.

**Comment by cezarsa** [comment]
Hi there, there's a probable fix for this issue already committed. Would you mind downloading current source [1] and testing it as a unpacked extension to see if it solves your problem?

[1] - http://github.com/cezarsa/chromed_bird/zipball/master

**Comment by speener** [comment]
That did appear to fix the problem.

**Comment by cezarsa** [comment]
Great! I'll publish this new version to the gallery ASAP.
