### ISSUE TITLE
Multiple account support and capability to to use both Twitter and Identi.ca

### ISSUE THREAD

**Issue by amanjeev** [cezarsa/silver_bird#216]
I was wondering if using both Twitter and Identica at the same time was possible.
Also, using multiple Twitter accounts.

**Comment by cezarsa** [comment]
Surely not a final solution, but you should be able to use http://crxclone.appspot.com to install more than one instance of Chromed Bird. Each one of them will be completely independent allowing multiple accounts this way. Just head directly to http://crxclone.appspot.com/extension/encaiiljifbdbjlphpgpiimidegddhic to install the clone.

**Comment by amanjeev** [comment]
Thanks. I tried it and the second account just does not work keeps crashing my Chrome.
