### ISSUE TITLE
Error on URL shortener (migre.me)

### ISSUE THREAD

**Issue by Fabinhuro7** [cezarsa/silver_bird#217]
I got the following error when I click on the little world that used to automatic short the URL from the page I was visiting:

"Error 0 : OK" 

Even if paste the link to the URL shortner window, I still get the same message.

**Comment by cezarsa** [comment]
Fixing migre.me shortener. Wth people, start versioning your APIs! Closed by e6fc35beb51fcc56791211dc3f3e2dc4d191c8b8
