### ISSUE TITLE
Can't remove tabs on Mac

### ISSUE THREAD

**Issue by vbalta** [cezarsa/silver_bird#218]
I'm trying to remove some tabs and can't figure out how to do it. I think it's a "right-click" thing, but I'm on a Mac and have just one mouse button. I tried control-Click, but that didn't work. 

Any suggestions, or is this something that needs to be fixed? Thanks.

**Comment by cezarsa** [comment]
Allowing ctrl-click as a way to show the context menu. Closed by 8a459184769768bec4c866f93838ca88fde05353

**Comment by cezarsa** [comment]
A fix for ctrl-click should be on the next release, meanwhile, have you tried enabling the secondary click option in system preferences -> mouse ?

**Comment by vbalta** [comment]
Great. Thanks for the coming fix. Secondary click option worked, too. Didn't know that was possible. Thanks for the tip!
