### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by jsbeckr** [cezarsa/silver_bird#23]
In ver 0.51 the time between clicking on the bird button and the appearing of the popup has increased. At least this is my feeling. I tested that issue on my desktop and my laptop and on both it is slower than before.

**Comment by cezarsa** [comment]
I noticed that too, hopefully commit cd414b303ddd55a541ebd3288283bdc3990f9d36 will improve it.

**Comment by cezarsa** [comment]
Commit 6419bb8dfb33af73794db0191ca039d50c03cfe6 also addressed a big performance bottleneck. I'm closing this issue for now. If the problem persists after the new release we can reopen it. (BTW, next version is due to tomorrow.)
