### ISSUE TITLE
Show new tweets as soon as they arrive.

### ISSUE THREAD

**Issue by cezarsa** [cezarsa/silver_bird#24]
Show new tweets inside current page through DOM manipulation in a content script that will be loaded in every page.
This content script needs some kind of lazy loading for performance reasons, we don't want to slow down every website because of our content script. I'm thinking of something like dynamically adding a <script> tag to the DOM only if we've new tweets to show. So, initially, the only impact in the current page would be one call to the API (setting the communication channel with the extension).

**Comment by DanHerbert** [comment]
This would be nice if it could be added as an optional feature that can be turned on or off. I don't think I'd always want my tweets to display instantly all the time.

**Comment by cezarsa** [comment]
Notifying when new tweets arrive according to notification settings. Closed by a4e7aa9d8427d7f1ad7165914fa335a2e0b3cd71
