### ISSUE TITLE
Twitter's API URL will change to HTTPS when using my own API automatically

### ISSUE THREAD

**Issue by ayanamist** [cezarsa/silver_bird#240]
in china, twitter is blocked, so we must use our own api address instead of official api address.
if you specify Twitter's API URL in HTTP and keep API Signing URL in HTTPS, it will change back to HTTP for API URL.
i look over the code and find it's caused by lib/twitter_lib.js line 120-125.
author think it should try HTTPS if empty response, but if user is using his own API, usually no HTTPS at all. and this method breaks all request in the future(all will go through HTTPS which in fact is not accessible).
i think these code is not necessary any more, because HTTPS api is seldom seen and Twitter Official API is not using HTTP any more

**Comment by cezarsa** [comment]
Right, it's time for this code to stop existing.

**Comment by cezarsa** [comment]
Since we now default to https API endpoints we shouldn&#39;t mess with user&#39;s manually configured endpoint. Closed by 6bdd18315c7a0dca4397c8aab807e1c0708c002c.
