### ISSUE TITLE
Open links in background

### ISSUE THREAD

**Issue by kurtextrem** [cezarsa/silver_bird#243]
Hi,
It would be great, if there is an option, where you can configure, if you'd like to open a link in background or in foreground!
(often i click every link in my timeline, and so chromed bird closes, caus' the link was opend in foreground :/)

**Comment by jmlind** [comment]
All of the browsers I have used support middle mouse button (the scroll wheel) to open a link in a background tab. This method works for me with Chromed Bird as well, so give it a try.

**Comment by kurtextrem** [comment]
https://github.com/cezarsa/silver_bird/pull/304
