### ISSUE TITLE
Unrelated tweets in search tabs

### ISSUE THREAD

**Issue by rcfox** [cezarsa/silver_bird#247]
In the past few days, I've been getting tweets that are completely unrelated to the search terms in search tabs (the search term isn't even in the tweet). If I change the search term, and then change it back, I get the expected results, but after a little while, more unrelated stuff creeps in.

**Comment by cezarsa** [comment]
That's really odd and shouldn't happen. Do you have a screenshot showing an example of such a case?
One of my guesses would be related to Twitter constantly filtering the public stream for spam tweets but only after making then available to the search API. That would explain why redoing the query doesn't show the unrelated stuff showing up, but it's just a wild guess. I'll investigate this further.

**Comment by rcfox** [comment]
I can't seem to take a screenshot while Chromed Bird is open. Whenever any sort of menu thing is open, most of my window manager functions stop working. (I'm in Ubuntu, using Compiz. Perhaps I should log a bug in their tracker!)

Some tweets that show up in my search for "RyanFox" are:
http://twitter.com/#!/mattNCL/status/37416579662618624
http://twitter.com/#!/_Afrosentriese/status/37417686073999360
http://twitter.com/#!/nendz/status/37420954888048640
http://twitter.com/#!/ainokuni/status/37453862868619264
http://twitter.com/#!/TYPHN_JP/status/37454239588425729
http://twitter.com/#!/dianablade/status/37454264758571008
http://twitter.com/#!/drkeebs/status/37512984033099776
http://twitter.com/#!/JoeCeguinho/status/37512998578814976
http://twitter.com/#!/JBieberomance/status/37513035358674944

There seem to be some specific patterns to the tweets showing up, but none of them seem to be related to "RyanFox".

**Comment by mjdominus** [comment]
I reported this problem already, with screenshots and window dumps, but you closed the issue today without replying. (http://bit.ly/fCfOGD)  You can find the screenshots at http://plover.com:8080/~mjd/misc/ChromedBird/ .
