### ISSUE TITLE
"Error -1: AJAX request failed (bad connection?)" when trying to share a page

### ISSUE THREAD

**Issue by JohanKlos** [cezarsa/silver_bird#249]
I was on this URL and tried to share it using the little globe:
http://www.smashingmagazine.com/2011/02/25/why-wait-for-the-opportunity-create-your-own/

I got this error message:
X
Error -1: AJAX request failed (bad connection?)

Thoughts?

**Comment by cezarsa** [comment]
What URL shortener are you using? I just tested it with bit.ly and it worked fine.

**Comment by JohanKlos** [comment]
tr.im
and you're right, that was the issue >.<
