### ISSUE TITLE
Empty desktop notifications after a full screen

### ISSUE THREAD

**Issue by beckr** [cezarsa/silver_bird#252]
After I had watched a movie in full screen (with VLC for example), with chrome opened, desktop notifications no longer appears on top of VLC. Instead they appear (and they stay) in background but with no tweet content. I have to close all those empty notifications until there are no more unread tweets.

I have chromed bird 1.9.6.6, chrome 11.0.686.3 dev, and Win 7 x64.
I can make a screenshot if it is useful.

**Comment by beckr** [comment]
Here the screenshot
http://img852.imageshack.us/img852/677/39669623.png

**Comment by oddtoddy** [comment]
Same problem here.

**Comment by cezarsa** [comment]
Fixed in 1.9.7.0. Thank you for reporting this problem.
