### ISSUE TITLE
Vertical scrollbar missing/broken in attached mode

### ISSUE THREAD

**Issue by buzzz** [cezarsa/silver_bird#253]
The vertical scrollbar is either missing completly or is only displayed in half which means that the button to scroll down is not visible. It seems to be half of the bar is beyond the window and not visible.
In detached mode all works perfectly.

Chromebird version 1.9.6.6
Google chrome version 10.0.648.127 beta
OS Win7 32bit

**Comment by cezarsa** [comment]
Adjusting maximum popup height according to window size. Closed by 13979e247107ac159ad5e6109d5e73ad7fb01c08.

**Comment by cezarsa** [comment]
Please, try clicking on the "Reset Popup Size" button on the options page, it should fix this issue.
