### ISSUE TITLE
Possible problem on twitter_lib.js

### ISSUE THREAD

**Issue by thiagomarinho** [cezarsa/silver_bird#258]
I didn't find anything about it, so lets go.

I believe there's a little issue on twitter_lib.js file (last version). On ajaxRequest() method the url https://api.twitter.com/1/ is never called for requests like users/lookup, so (in this case) response have just one entry, despite the number of ids passed.

Sorry for bad english, brazilian friend :]

**Comment by cezarsa** [comment]
Hi Thiago,
Sorry, but I could not find the reported issue. The base API URL is always prepended to the resource path. Check https://github.com/cezarsa/chromed_bird/blob/master/lib/twitter_lib.js#L86-86

I've just checked and users/lookup is returning the correct results here.

BTW, I'm also brazilian. :)

**Comment by thiagomarinho** [comment]
Curious, because here it was not working until I change the url (hard-coded). Probably my configuration was wrong...

(abração rapá! grande trabalho :])
