### ISSUE TITLE
Support favorites

### ISSUE THREAD

**Issue by imcdnzl** [cezarsa/silver_bird#26]
I often use favorites to mark tweets to read later. It would be great if chromed_bird supported this also.

First priority for me would be able to mark them, second priority to go and view them.

**Comment by andrewrjones** [comment]
I would also like to see this, although there is a risk of the interface becoming cluttered.

**Comment by cezarsa** [comment]
First part is supported by 16c295273f38a15b40286719554c21b4b9623950 Hang on for the next release.

**Comment by andrewrjones** [comment]
Excellent, thanks for the very quick turn around :-)

**Comment by cezarsa** [comment]
Adding favorites timeline. Closed by 33356aa4d85893c2ee2d8271d11a30de67f7aba2
