### ISSUE TITLE
crxclone doesn't work

### ISSUE THREAD

**Issue by PocketGoddess** [cezarsa/silver_bird#268]
I'm trying to use the clone service to install two instances of Chromed Bird to manage my two twitter accounts, but I get an internal server error every single time.

I'm running Chrome 11.0.696.34 beta on Windows 7.

**Comment by cezarsa** [comment]
Some recent changes to GAE broke it. I'm already working on fixes.

**Comment by cezarsa** [comment]
Okay, up and running again. Thanks for reporting.
