### ISSUE TITLE
Error when pressing alt+tab

### ISSUE THREAD

**Issue by queimporta** [cezarsa/silver_bird#27]
I'm using Chomed Bird 1.0.1 and Chromium 4.0.267.0 and when I press alt+tab twice the extension screen gets totally messed up and pressing the bird icon the problem gets fixed

Screenshot: http://img195.imageshack.us/img195/2897/screenshotxs.png

**Comment by cezarsa** [comment]
Yeah, I just found what's causing this, it's related to the themes selector. But don't worry it should get fixed in the next release as the theme selector will go to the options page.

**Comment by cezarsa** [comment]
It's been fixed by disabling on the fly theme changes. Closing this issue.
