### ISSUE TITLE
Clicking Icon Should Expand/Collapse ChromedBird

### ISSUE THREAD

**Issue by StrikerObi** [cezarsa/silver_bird#270]
In the current version, when you click the ChromedBird icon, the extension appears. While the extension is open, if you click the icon again it simply re-loads the extension. To close the extension, you currently need to click outside of the icon/extension. If the app is open, clicking the icon should instead collapse it, rather than reload it. At the very least, this should be a user-definable option.

**Comment by kurtextrem** [comment]
This is a Chrome limitation and you can't change it.

**Comment by StrikerObi** [comment]
Lame. Oh well. That's a very strange limitation, since the expand/collapse behavior works properly when clicking on a folder in the bookmark bar, and on the Settings button which is directly next to my ChromedBird button. Not allowing extensions this behavior creates annoying inconsistencies in the UI/UX.
