### ISSUE TITLE
Tweets showing up twice

### ISSUE THREAD

**Issue by allshallfade** [cezarsa/silver_bird#278]
Every tweet I post shows up twice in my chromed bird timeline, but when I look at my actual profile, or even just my tweets page within chromed bird, it's only there once. I tried uninstalling and reinstalling the extension, but it's still happening. It's not a major issue, since I don't think anybody else is seeing my tweets twice, it's mostly just annoying and I don't understand why it's happening. Any ideas?

**Comment by cezarsa** [comment]
Fixed on 1.9.7.7. Please give it a try.
