### ISSUE TITLE
Retweets from unauthorized persons

### ISSUE THREAD

**Issue by chicocvenancio** [cezarsa/silver_bird#279]
Lately I have been receiving retweets from the people that I follow but have disabled their retweets from my timeline. Since I do this to a couple of people that retweet over 40 times a day it becames a real problem. 
In the web the twitter is normal, no retweets from unauthorized persons.
Thanks for this great extension.

**Comment by cezarsa** [comment]
Hi there, I'm still looking for a solution for this problem. After switching to the streaming API twitter is just sending everything and apparently it doesn't provide a way to identify whether retweets are enabled or not.

For now the solution is disabling streaming: Go to the options page and uncheck the "Use streaming API" checkbox. You may need to restart Chrome for this to take full effect currently.

**Comment by chicocvenancio** [comment]
What would I actually miss without the streaming?
