### ISSUE TITLE
Support Open Source microblogging tools

### ISSUE THREAD

**Issue by remin13** [cezarsa/silver_bird#28]
Hi,

Please support Open Source microblogging tools like identi.ca OR status.net
it will more happy news for opensource lovers!!!

Cheers,
Remin Raphael

**Comment by andrelop-zz** [comment]
I'm voting for this feature as well. Currently, I'm having a hard time trying to keep using my Identi.ca account under Google Chrome. Chromed Bird allows me to use Twitter, but I would really like to be able to use both Twitter and Identi.ca from within a single Google Chrome extension.

As Chromed Bird is my extension of choice for microblogging it would be awesome if one could use it to access/use his/her Identi.ca account as well.

**Comment by cezarsa** [comment]
Seamlessly supporting identi.ca microblogging service. Just switch the microblogging service in the options page. closed by a73a0834dc886de5d58b7d2663db48842453fbac and closed by a73a0834dc886de5d58b7d2663db48842453fbac
