### ISSUE TITLE
Main Twitter website

### ISSUE THREAD

**Issue by nutcracker84** [cezarsa/silver_bird#280]
Hi,

I don't know if this has been addressed before but here goes.
1. After installing the extension, I cannot login to login to twitter using Chrome with the URL www.twitter.com.  I have to use https://api.twitter.com/
2. When I click on a name in Chromed bird and then click on Profile, it tries to go to twitter to open the profile, but it goes to http://twitter.com/#!/User_Name which does not work. If I change the URL to https://api.twitter.com/#!/User_Name, then I can visit the profile.

Thanks,
Tony.

**Comment by cezarsa** [comment]
Hi, I can't see how the extension could be responsible for www.twitter.com not working.
Have you tried uninstalling the extension to check whether you continue to see this behavior?

**Comment by nutcracker84** [comment]
I did that and I think you're right. This is my issue. I don't know why though.
