### ISSUE TITLE
Support reply to more than one person

### ISSUE THREAD

**Issue by zellux** [cezarsa/silver_bird#30]
In the Firefox plugin Echofon I can click more than one person and reply them in the same message, but which I means clicking a person's name will add @name to the beginning of the message. I think it will be more convenient if Chromed Bird can support this feature as well :P

**Comment by elijahmanor** [comment]
I'd like this feature as well... as I sometimes comment to multiple people at once and it would be nice to click reply on the people I want (appending their twitter ids) and then be able to type a message to all of them. TweetDeck has this support

**Comment by cezarsa** [comment]
Okay, that's the one thing I want to focus right now. It's a really useful missing feature. I also intend to create some kind of autocompletion, when users type @ or "d " Chromed Bird would show a list of people you're following.

**Comment by cezarsa** [comment]
Okay, no autocomplete yet, but clicking the names already work: 54cb8ec467d7dbebe238f429a4350b7aa4a6a188

**Comment by hyperlink** [comment]
I have an implementation of this but I wonder if it should be a options setting since it might throw some users off. Thoughts?

**Comment by pmbarros** [comment]
One small problem with the current implementation: you usually don't want to reply to yourself, so the users' own @name should not appear. For example, if I'm @11111 and I want to reply a message that @22222 sent to myself (@11111), @33333 and @44444, the reply should be sent to @22222 @33333 @44444. Current implementation sends to @22222 @11111 @33333 @44444.

In other words, reply to all should reply to every user mentioned EXCEPT the current user himself, just like what happens with email.

**Comment by hyperlink** [comment]
Already in :)

062f587c4a6e654bcabea244d8e258578aed78f9

**Comment by cezarsa** [comment]
Closing this issue. I'm going to open a new one for the autocomplete stuff.
