### ISSUE TITLE
Unexpected error "undefined"(Forbidden) updating tweets. Try again (like issue #64)

### ISSUE THREAD

**Issue by mbrand1** [cezarsa/silver_bird#300]
I saw this reported earlier.  I'm seeing the same thing, however, only when I click the extension icon after leaving off in either the Unified or DM tabs.  If I come back when in Home, @user, or Favorites, I see tweets and everything is fine.

I'm using Silver Bird 1.9.8.2 Chrome 13.0.782.32 beta on Debian Linux

**Comment by yang** [comment]
I'm also seeing the same problem. This only started happening I think yesterday or so.

Basically, the Home, @user, and Favorites tabs work, but Unified and DM don't.

**Comment by DIL23** [comment]
ditto since around yesterday 30th June 2011

using
Chromium 12.0.742.91 (87961) Ubuntu 11.04

**Comment by cezarsa** [comment]
Sorry for that guys, I've just published version 1.9.8.3 a few minutes ago and it should fix this problem. To force an update just download it again from the gallery.
