### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by chemicalsandgin** [cezarsa/silver_bird#302]
I accidentally deauthorized my account, when I try and reauthorize:

clicking on silverbird icon >  request new token > taken to twitter page and clicking "authorize app" > it says authorization was successful 

however, when I go back to silverbird it asks me to authorize again. 

I've try completely uninstalling and reinstalling but it just does the same.

**Comment by cezarsa** [comment]
This is odd and should not be happening...

To help me isolate the problem, could you try opening the options and in the Timelines section uncheck the options "Visible" and "Include in unified timeline" for the DMs timeline. After you do that, click the icon, authenticate again if necessary and tell me if it still keep asking you to authenticate again.
Thanks.

**Comment by chemicalsandgin** [comment]
Gave it a go but it's still asking for authentication

**Comment by chemicalsandgin** [comment]
Didn't mean to click close sorry! >.<

**Comment by chemicalsandgin** [comment]
I finally managed to get it working after uninstalling/reinstalling a bunch of times.
