### ISSUE TITLE
Tweets abruptly stop being displayed on timeline

### ISSUE THREAD

**Issue by denzilc** [cezarsa/silver_bird#31]
I happens quite a number of times that tweets stop appearing on the timeline which is a real (and probably ONLY) turn-off for this application.  
Requesting to look into it.

**Comment by cezarsa** [comment]
Hi, I've not been able to reproduce this, but I have some suspicion that it's related to Twitter's API rate limit.
Please, when this problem happen again could you check the "Remaining Twitter API Hits" field in the Options page?
If it's 0 then that's the problem. Usually consuming the rate limit too fast is an issue when you use multiple Twitter clients at the same time, as they are all consuming from the same limit.
To avoid this problem you can tweak the "Refresh Interval" values in the options page.

**Comment by denzilc** [comment]
Thanks mate, problem solved !
PS: Apologies to reply late and behave like an ass !

**Comment by denzilc** [comment]
Thanks

**Comment by cezarsa** [comment]
NP, I'm glad to hear that it's working. I'm closing this issue and I'll open a new one so I can remember to warn users when their API limit wear out.
