### ISSUE TITLE
Use own url shortener credentials

### ISSUE THREAD

**Issue by DanAtkinson** [cezarsa/silver_bird#32]
Basically, I'd like to be able to pass in my own username and password for a url shortening services such a bit.ly.

Please!

**Comment by livin52** [comment]
+1

**Comment by cezarsa** [comment]
Thanks to our newest contributor, ceykooo, this issue was closed by commits f194962a50897a78a396aa8524c793309b2562bc and 12def709159f53d19236e3c9bc6b42ee3eb4e78f

**Comment by DanAtkinson** [comment]
Sweet! Thanks!
