### ISSUE TITLE
Mute feature

### ISSUE THREAD

**Issue by msmosso** [cezarsa/silver_bird#320]
It would be awesome to have the possibility to mute someone (forever or just for a specific time). I hate when my followers decide to flood my timeline, and, in other case, those who will ask me why i unfollowed them.

Best Regards,

Matheus

**Comment by pollecuttn** [comment]
I too would love this. For example someone live tweeting an event is really annoying if you're not interested. Mute would be great so you wouldn't have to unfollow then remember to refollow later on.

Thanks!
