### ISSUE TITLE
Reply to DM Produces an @reply

### ISSUE THREAD

**Issue by zebdro** [cezarsa/silver_bird#33]
I read a dm. I hit Reply, and I expect to see "d user" in the composition window. 
Instead, I see @user. 
I presume this sends a public reply, but I did not test.

**Comment by cezarsa** [comment]
Yep that's a bug, it has been fixed by commit 0e630c5ffacec5692c459dfe5b09c5533b20f3e1 but I haven't released it yet. I'll probably release a new version latter today and this bug will be gone. Thanks for reporting.

**Comment by cezarsa** [comment]
1.2 was released and fixes this bug.
