### ISSUE TITLE
Notification Icon Customization

### ISSUE THREAD

**Issue by brettsnyder** [cezarsa/silver_bird#34]
I would love to see some sort of notification that you have mentions/replies instead of simply all tweets in your timeline.  It's important for me to know when a reply is made, so it could either have a unique color for the bird when a reply comes in or simply the ability to only receive updates when mentions/replies are made.

**Comment by cezarsa** [comment]
Customizing icon notifications. closed by 51267be653aa8eba93f00323ecef605fdc2c2033 and closed by 51267be653aa8eba93f00323ecef605fdc2c2033

**Comment by brettsnyder** [comment]
Thank you - This extension is fantastic
