### ISSUE TITLE
Is there a way LIMIT to # of tweets displayed at one time? 

### ISSUE THREAD

**Issue by wikiexpert001** [cezarsa/silver_bird#344]
How do I STOP the 50+ tweets after unlocking computer after being gone a while? The lower corner keeps displaying SO MANY notifications. I WANT Home tweets, but I also want to be able to shut so many at one time down. 

Is there a way LIMIT to # of tweets displayed at one time?

**Comment by cezarsa** [comment]
Change the "Notifications at once" option on the options page.

**Comment by wikiexpert001** [comment]
Notifications at once (-1: all):

DOES NOT work. It STILL puts 50 tweet notifications on computer even if its set to 
"Notifications at once (-1: all): 5". Am I doing something wrong?
