### ISSUE TITLE
Authorization Problem

### ISSUE THREAD

**Issue by brokengolem** [cezarsa/silver_bird#357]
Suddenly started having a problem with Silverbird. The twitter authorization won't take. I will authorize it, but the extension won't remember that I've done so. Auto-authorization happens too quickly to obtain the token # and enter it manually. Twitter lists it as an authorized app, so thinking it's a problem on the Silverbird side. Tried reinstalling multiple times and updated chrome. Nothing seems to work :(

**Comment by g10lafleur** [comment]
having the exact same issue - gotta get my silver bird back - thanks!

**Comment by ghost** [comment]
here too.

**Comment by lewismath** [comment]
same.

**Comment by j0k3r** [comment]
It's a twitter issue https://dev.twitter.com/issues/360

**Comment by ferasn88** [comment]
Me too !

**Comment by cezarsa** [comment]
Sadly, as @j0k3r noted, twitter has been acting weird.
I tried a small workaround on Silver Bird 1.9.8.11, could you guys update it and tell me if it solves the problem?

**Comment by brokengolem** [comment]
Thanks for the quick response! Just installed the upgraded. " "Could not authenticate with OAuth."(Unauthorized)" was the new error I received, but within Silver Bird and it didn't keep opening the twitter authorization page. So progress!

**Comment by lewismath** [comment]
I got the same result as brokengolem. Thanks for your efforts! :D

**Comment by cezarsa** [comment]
Okay guys, one last shot, just upped 1.9.8.12, please give it a try.
If it doesn't fix the problem Twitter will probably have it fixed by tomorrow (https://dev.twitter.com/discussions/7913?page=1)

**Comment by brokengolem** [comment]
My lists and DMs work, but that's it. Good to know twitter is looking in to it. Thanks for everything cezarsa, and, while I have the opportunity, thanks for Silver Bird. Much love :)

**Comment by brokengolem** [comment]
Silver Bird seems to be up and running at full strength! Thanks for everything :)
