### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by utah777** [cezarsa/silver_bird#358]
Cannot create Silver Bird clone anymore. A fix would be HIGGLY appreciated !

**Comment by cezarsa** [comment]
It should be working again now, thanks for letting me know.

**Comment by utah777** [comment]
Now I'm told an extension can only be installed from Chrome webstore, no
third party sources.

Any workaround to this?

Best regards,
- Sergey

On Sat, Jun 30, 2012 at 8:08 PM, Cezar Sá Espinola <
reply@reply.github.com
