### ISSUE TITLE
Mark All As Read button

### ISSUE THREAD

**Issue by DanHerbert** [cezarsa/silver_bird#36]
It would be nice to have a way to mark all tweets as read, or a way to mark individual tweets as read more quickly than hovering over them for a few seconds.

Many people read their tweets from more than one device/computer, so "unread" tweets can easily stack up if you read them from other sources.

**Comment by cezarsa** [comment]
Correctly showing new tweets count and adding an option to read all tweets. Closed by 34dcb11231067b6622f323a37d5ffd250d8ae925 and Closed by 34dcb11231067b6622f323a37d5ffd250d8ae925.
