### ISSUE TITLE
DM reply MAJOR error

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#37]
When replying to a DM it doesn't send a DM, it sends a public tweet.

**Comment by livin52** [comment]
Also, the RT and Share buttons in the DM tab are useless...

**Comment by livin52** [comment]
Exists: http://github.com/cezarsa/chromed_bird/issues/#issue/33

Sorry.

**Comment by cezarsa** [comment]
NP. It was fixed in 1.2 by 0e630c5ffacec5692c459dfe5b09c5533b20f3e1
