### ISSUE TITLE
Closing "Compose" area bug.

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#38]
Closing the "Compose" area doesn't shrink the whole popup.

**Comment by cezarsa** [comment]
That's an old bug from Chrome that was fixed at some point but seem to be back in 4.0.266.0. I'm trying to get some feedback from Chrome developers.

**Comment by cezarsa** [comment]
Watching these two issues from Chrome: http://code.google.com/p/chromium/issues/detail?id=30291 and http://code.google.com/p/chromium/issues/detail?id=30294

**Comment by cezarsa** [comment]
Okay Stable channel and Beta channel don't have this issue anymore. Now it only happens on Dev channel, and should be fixed soon in Chrome 5, so I'm closing this issue.
