### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#39]
It would be nice to have a link to Twitter.com

**Comment by steve-crabb** [comment]
I would also like to see this - I know we can click on people's names to open Twitter in a new tab to their timeline, but a link to twitter.com would allow me to remove Twitter from my bookmarks bar :-)

**Comment by bpaf** [comment]
I would love if there was an option so that clicking the bird in the bar would bring you to twitter.com instead of the "page pop up."

Thank you.

**Comment by sdenike** [comment]
You can always right click on their name then go directly to their profile
