### ISSUE TITLE
Replying to a tweet that mentions multiple people only adds the sender

### ISSUE THREAD

**Issue by DanAtkinson** [cezarsa/silver_bird#398]
Steps to reproduce:
1. Ask someone to send you a tweet and mention two people in that tweet.
2. Click the reply function in Silver Bird.

What I expect to see:
All users mentioned in the first tweet to be mentioned in your reply.

What I actually see:
Only the sender of the tweet is added to the reply.

Anything else?
If this seen as desirable, then a 'Reply All' feature should be created.

**Comment by dorry-kun** [comment]
As far as I know this can be changed in the options. Under UI there's a box for "reply to all mentioned."
Perhaps due to an update mine became unchecked quite recently, so that might be your case also.

**Comment by DanAtkinson** [comment]
You're right! Thanks for clarifying! I'm surprised this isn't enabled by default.

Kind regards, Dan
