### ISSUE TITLE
Theme selector

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#40]
Move the theme selector to the options page.

**Comment by steve-crabb** [comment]
+1

Or at least have the option to not display it on the main panel. Will make the interface look a little cleaner for those who don't use it.

**Comment by cezarsa** [comment]
Yep, it really doesn't make much sense changing themes on the fly. I'm planning in keeping the combo box with a different purpose though, it'll be quite useful to support lists.

**Comment by cezarsa** [comment]
Supporting Twitter's lists. closed by 83a684418938eabb49bcf6cb9acf415c56d86771 and closed by 83a684418938eabb49bcf6cb9acf415c56d86771
