### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by alextakitani** [cezarsa/silver_bird#44]
Allow a always on top option, so i can continue reading my tweets after clicking on links. Echofon for firefox behaves like that.

**Comment by cezarsa** [comment]
Have you tried clicking the link with middle button? The popup will remain open if you either middle click or Ctrl-click the link. It's not possible to change tabs and let the popup still open though.

**Comment by alextakitani** [comment]
Wow! Sorry, didn't tried it. Works perfectly.

**Comment by cezarsa** [comment]
Cool, I'll close this issue, and I just got another question for the upcoming FAQ. :)

**Comment by andrewrjones** [comment]
On Linux, the popup stays open when I change tabs. Not sure which is the intended behaviour.
