### ISSUE TITLE
Padding(?) Bug

### ISSUE THREAD

**Issue by mtmccurdy** [cezarsa/silver_bird#46]
Hello -- I've found a bug.  

Mac OSX 10.6.2, Chromium 4.0.270.0 (34432), Chromed Bird 1.20

First, yes I do know that things are far from perfect using the mac builds right now, but:

The theme "Whispers" works perfectly, with the new icons to reply, etc, on the right side of the tweets.  The bug, however, is that with the default theme "Chromified," there seems to be some kind of padding error such that the four graphic icons appear on the right side but underneath the tweet content.  This has the effect of doubling the length that a tweet takes up in Chromed Bird even though there is no text at the bottom.  

I wouldn't have reported it on mac except that, as I said, Whispers works perfectly, only Chromified is broken.  

EDIT:  Seems to have fixed itself with a restart.  Very strange.

**Comment by cezarsa** [comment]
Glad to hear it fixed itself. :) I don't have a Mac so it's kinda hard to me to test on it. However this bug may be related to dynamically changing themes, and this is one thing I'll probably disable for the next release, only allowing theme changes through the options page.
