### ISSUE TITLE
Copy & Paste 

### ISSUE THREAD

**Issue by RayWaldo** [cezarsa/silver_bird#47]
The right-click menu does not operate on the main compose window. Ctrl-V does work but that is old school and many new users may not know it. I tried to paste info into the window w/o success many times before I remembered to try Ctrl-V.

**Comment by livin52** [comment]
+1

If I wanna change the browser's active dictionary, I can't....

**Comment by cezarsa** [comment]
Actually that's a limitation from Chrome itself. There seem to be no way to show the default context menu. I could create a DHTML menu but it would be quite limited. I think copy and paste would be possible, but changing current dictionary wouldn't.
I think there's a Chromium issue about this, I'll check it out and report back to you.

**Comment by JeffMelton** [comment]
Command + V (Mac) does NOT work.

**Comment by asb** [comment]
I think [this is the relevant issue](http://code.google.com/p/chromium/issues/detail?id=28226).

**Comment by JeffMelton** [comment]
@asb That's only relevant to mouse gestures, if I'm reading it right. I could deal with not being able to right-click if I could Command+C{X,V}.

**Comment by alex3t** [comment]
Yes missing of cmd+c/cmd+v on mac is most worstest issue of chromed_bird for me. Cezarsa, please, up this bug to top of your query

**Comment by asb** [comment]
The suggested solution on that bug report is to provide an API to display the native context menu. The existence of such an API would seem to solve Chromed Bird's problem.

**Comment by cjmcqueen** [comment]
Yeah, this is really annoying.  Please find a way to fix the copy/paste issue on the Mac.

**Comment by Ikke** [comment]
As already said, this is a lacking feature of chrome. You have little control over the chrome UI in an extension.

**Comment by cjmcqueen** [comment]
I guess I understand how it's an issue with the right-click menu, but I don't understand how the hotkeys are getting blocked (cmd+c or cmd+v).  I'm not saying it's the extension's fault, just that it's weird.  Do we need to put pressure on the Chrome Dev's to fix this?

**Comment by cezarsa** [comment]
Hey guys, sorry for the delay in answering this thread. So, I've found 2 open Chromium issues related to copy and paste problems.
You can put some pressure on Chrome developers by starring these issues:
http://code.google.com/p/chromium/issues/detail?id=30058
http://code.google.com/p/chromium/issues/detail?id=33912

**Comment by chrisrueger** [comment]
I commented and voted at http://code.google.com/p/chromium/issues/detail?id=30058 
Make sure that you click the "star" icon to vote for this issue.
