### ISSUE TITLE
Additional scrollbar is visible

### ISSUE THREAD

**Issue by srid** [cezarsa/silver_bird#48]
I see an additional scrollbar surrounding the Chrome Bird mini-window. Please see the screenshot: http://dl.dropbox.com/u/87045/permalinks/cbird-sbar.png

Windows 7 64-bit | Chrome 4.0.266.0 | "size of text and other items" (DPI) set to Medium - 125% http://dl.dropbox.com/u/87045/permalinks/dpi.png

Oh, and thank you for this wonderful and simple extension!

**Comment by cezarsa** [comment]
I disabled overflow scrollbars in some moment I can't remember now, so they are probably not showing anymore.
However there's still some issues when content is too big to fit the popup window, but there's already another issue for that, so I'm closing this one.
