### ISSUE TITLE
RT's or Replies

### ISSUE THREAD

**Issue by sickyd** [cezarsa/silver_bird#49]
When you RT, "Share" or Reply to someone, after you send off the reply or RT, the window scrolls back up to the top of your timeline. It would be nice if it stayed at the current location that you were scrolled at, like it does when you click on a link in a tweet. It would be useful when catching up on a backlog of tweets.

**Comment by cezarsa** [comment]
Keep current scroll after sending a tweet. Closed by 81951c12a2c178ae43857c19546525d96ffd21de
