### ISSUE TITLE
Resize popup after composing tweet.

### ISSUE THREAD

**Issue by jsbeckr** [cezarsa/silver_bird#5]
The popup doesn't resize back after the "fade-in" of the tweet-textbox.

**Comment by cezarsa** [comment]
Unfortunately this is a known Chromium issue as reported is http://code.google.com/p/chromium/issues/detail?id=26471
I'll leave this issue open until it gets fixed on the dev channel.

**Comment by cezarsa** [comment]
Yay! Looks like it's been fixed on trunk, let's wait until the next dev channel release.

**Comment by cezarsa** [comment]
Fixing some bugs and improving error handling with OAuth. Also closed by 0544c1f979dc07ea13c76586f049327bc0fec757
