### ISSUE TITLE
System clock: add a warning message if authentication error occurs

### ISSUE THREAD

**Issue by yporti** [cezarsa/silver_bird#50]
I use Chromed Bird in Gentoo Linux and had this error:

"Ouch... Something bad happened to Chrome Bird while calling Twitter's API.\n\nPlease try clicking the icon again to restart the authentication process. Failed to validate oauth signature and token."

The problem wasnt in the extension, but in system clock that was wrong. So, I suggest that an additional message informing the User that the problem may be the system time.

And thank you for this great extension. :)

Regards.

**Comment by cezarsa** [comment]
Hey yporti, thanks for reporting this. I've investigated this problem in the past and have came to the same conclusion as you, I even added a FAQ entry about this: http://wiki.github.com/cezarsa/chromed_bird/faq
But you're right, the error message should be more specific about what might be causing the failure. I'll change this message.

**Comment by cezarsa** [comment]
Better error message for failures during requestToken. Closed by dace8113cd5a7d682a0f8eff91d9d973a87e8278
