### ISSUE TITLE
Enter to publish

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#51]
Twitter do not support line breaks. It would be nice that the enter publishes the tweet... xD

**Comment by livin52** [comment]
Never mind... Found out that you Ctrl+Enter works...

**Comment by Naouak** [comment]
I still think that enter would be great.

**Comment by cezarsa** [comment]
And I still think Enter might lead to a lot of accidental tweets. Anyway, it should be easy to add a configuration option for that, then everyone would be happy. :)

**Comment by cezarsa** [comment]
So, now we're officially supporting line breaks in tweets. Although Twitter's website doesn't show them, I came to know that other clients show, and it would be nice if we did the same. Because of that I don't think it'd be possible to support Enter to publish anymore so I'm closing this issue.
