### ISSUE TITLE
Layout/wrapping issue

### ISSUE THREAD

**Issue by mtmccurdy** [cezarsa/silver_bird#55]
Screenshot of the bug: http://imgur.com/Trqy2.png

I am using the latest Chromium nightly on Mac OS 10.6 and I'm having a bit of a problem with the layout.  I reported something similar that literally went away with no work on my part.  I realize that this likely has more to do with the fact that Chrome/Chromium on Mac is so woefully behind and little to do with your extension: but I don't know how to tell if a bug of this sort has been reported to Chrome, so I'll post this here anyway.

The dropdown for lists appears underneath the other tabs and appears to have 'wrapped' from where it should have been on the right.  Perhaps it is a padding error on Chrome Mac, don't know.  It does make things rather ugly though.

**Comment by andrewrjones** [comment]
I am getting the same problem on Windows & Ubuntu Linux

**Comment by mtmccurdy** [comment]
Ah, good to know.  So this does appear to be a real bug.

**Comment by cezarsa** [comment]
Yeah that's a bug in tabs overflow, I noticed it's happening when Twitter's username is too long. I'll fix that soon. Meanwhile you can disable some unused tabs so it doesn't overflow.

**Comment by mtmccurdy** [comment]
Ah thanks.  Disabling a tab works like a charm for now.

**Comment by cezarsa** [comment]
Partially fixed by c6383f9f3696e6ba42cb48bf27bc3c0acf76e85c. I still need to work on tweets resizing though.

**Comment by mtmccurdy** [comment]
Thanks cezarsa -- you're on top of it.

**Comment by cezarsa** [comment]
Allowing tweets to resize when popup expands. Closed by f9fb1d64716af41e2ca95baa2fc1c6b96928825e
