### ISSUE TITLE
Bugs in Lists

### ISSUE THREAD

**Issue by mtmccurdy** [cezarsa/silver_bird#56]
(I know, i know): Chromium Nightly, Mac OS 10.6

the second I click on the dropdown menu my timeline goes completely blank (all white space).  Allowing the Chromed Bird extension space to minimize and then opening it again causes the window size to be much shorter (no content below the row of tabs like Home, etc) and gives the error: Error "Undefined"(error).  This error will persist until you click on an actual list or click 'Home.'  

Clicking Home seems to then stop the bug from occurring.  Once I have done this I can click on the dropdown menu and the timeline does NOT go blank.  Very strange bug.  

Another small bug is that clicking "Home" does not reset the dropdown menu.  So I can click "Home" and still have my dropdown menu say that I am viewing the name of one of my lists.  I think it should reset to "- select a list -"

Sorry I can;t be more specific =/.  Having trouble recreating it myself at this point.

**Comment by cezarsa** [comment]
Hey there, I fixed a lot of stuff regarding lists and I'm pretty sure that's fixed in 1.4.8. Could you please try again in the new version? I'm closing this issue for now, you can open a new one if there's still any pending bugs.
