### ISSUE TITLE
Ampersands in regular URLs break link regexes

### ISSUE THREAD

**Issue by stephenmcd** [cezarsa/silver_bird#57]
If a URL in a tweet contains an ampersand, the string of text after the ampersand is treated as a twitter username and the username link is placed inside the already parsed URL. This is very uncommon however flickr.com photo URLs often contain an ampersand. My regex-fu is very rusty but I resolved the issue by changing the username regex to use the same approach as the hash tag regex which seems to take surrounding anchor tags into account. Change line 482 and 483 of product.html as per http://pastebin.com/f42ead82a

**Comment by cezarsa** [comment]
Fixing @mentions regex matching. Thx anonymous dude. Closed by 357800c9182ac4e7b1a54923a0ae23983604def1
