### ISSUE TITLE
Support link preview

### ISSUE THREAD

**Issue by spitfire2** [cezarsa/silver_bird#58]
http://www.clipotech.com/2010/01/hootsuite-updates-with-link-preview.html

**Comment by andrewrjones** [comment]
I would rather it didn't support this. Its not that useful a feature, and you can only fit so many features into a browser extension.

IMO if you want more from your Twitter client, use a full desktop client.

**Comment by cezarsa** [comment]
Commit 0347f11a7e3ac329e53ff70806c9c04db6b70d64 added an option to show original urls from shortened ones while hovering them. That's not the same thing hootsuite does but I think that's all I'm going to do to keep Chromed Bird fast and uncluttered, at least by now.
