### ISSUE TITLE
Buggy Animation

### ISSUE THREAD

**Issue by mtmccurdy** [cezarsa/silver_bird#59]
When the "Compose Tweet" bar is moved to the bottom the opening animation becomes quite choppy.

Additionally, the opening animation for the entire window is a bit choppy when clicking the Chromed Bird icon.

I'm running the latest Mac Dev on Mac OS 10.6.  Just wondering if other platforms are having trouble with choppiness in either of these two situations.

**Comment by ddlevine** [comment]
I'm running Chrome 6.0.472.62 (stable) on Windows XP SP3 and the animation seems to be smooth.

**Comment by cezarsa** [comment]
Yeah animations on OSX are not as smooth as in other platforms, especially when first opening the popup, there shouldn't exist any animation at all. There's a Chromium issue [1] related to that, you might want to star it.

[1] - http://code.google.com/p/chromium/issues/detail?id=56337
