### ISSUE TITLE
Adding Scrollbars to popup

### ISSUE THREAD

**Issue by jsbeckr** [cezarsa/silver_bird#6]
Adding scrollbars would ease the handling of more than 5 new tweets.

**Comment by cezarsa** [comment]
Do you think a scrollbar would be a better solution than the existing pagination icons?

**Comment by jsbeckr** [comment]
Yup, I think so. :)

**Comment by Chobblr** [comment]
i added a webkit scrollbar to the build i have, it seems to work well, and has fixed the flashing bug when the popup resizes :)

**Comment by cezarsa** [comment]
That's really cool Chobblr! Are you using the Git repository? If so you could use "git format-patch" to make a diff file and paste it as a GitHub Gist. Then I'd push your commit to the repository.

**Comment by Chobblr** [comment]
here is the pasted code : http://gist.github.com/229285 : you will have to change some things and it should not be added to any release yet unless ur taking snippets of the code due to the colour is wrong and some things i still like to tweak

**Comment by cezarsa** [comment]
Is it only a CSS change? I've updated it but I think I'm missing something, here it is how it looks in here: http://screencast.com/t/JowIu3J0
Feel free to keep tweaking on it. To fully support a scrollbar there'll need no be some changes to the javascript code. I'll probably work on it and on @'s and DM's tabs latter today or tomorrow. I'm thinking about having the tabs in the same place that today is occupied by the pagination icons. The scrollbar would be on the right side along the tweets timeline.

**Comment by cezarsa** [comment]
Improved navigation through older tweets with an endless scrollbar.
closed by 0dcc5773356cc088badedea523ba8009e2f4a1cb.
