### ISSUE TITLE
set a tweet read faster

### ISSUE THREAD

**Issue by Naouak** [cezarsa/silver_bird#61]
Is it possible to add a way to set a tweet read more faster than it is actually, like by clicking or by having the possibilities to change the time you need to hover it to make it read ?

Thanks.

**Comment by steve-crabb** [comment]
I agree - would like to see this too.

**Comment by cezarsa** [comment]
Yep, I also agree. :) Just clicking the tweet is simple and works well, I'll go for it soon.

**Comment by cezarsa** [comment]
Allowing tweets to be marked as read by clicking, also letting users configure hovering timeout. Closed by 172b9fedc1e3408dad800487543a2578b0d27735
