### ISSUE TITLE
Unselecting Home or Favorites Causes Whole Extension to Fail

### ISSUE THREAD

**Issue by elijahmanor** [cezarsa/silver_bird#62]
I am following a lot of people and tend to focus on my custom lists instead of the Home, but when I unselected the Home and/or favorites the extension only showed one tab with a @ in the tab header. It was unusable at that point. Adding back Home and Favorites and disable/enable makes it usable again, but I'd like to get rid of those tabs. Great extension by the way. I've been using it over TweetDeck last couple days.

**Comment by cezarsa** [comment]
Fixing crash when disabling home timeline. Closed by a7ce84556d3ff735e786051af2400a7b09b7c6a8
