### ISSUE TITLE
Support "unified" feed of DMs, mentions and normal messages

### ISSUE THREAD

**Issue by jskeet** [cezarsa/silver_bird#63]
While Chromed Bird doesn't make this as painful as other clients (particularly due to the little notification highlight) it would be nice to have an option of seeing a single feed of "all the stuff that might interest me" in one timeline - tweets from people I follow, mentions, and direct messages.

**Comment by Ikke** [comment]
How would you'd like to see this. Would this be just another feed?

**Comment by pmbarros** [comment]
Yes, that's the one feature I miss from twhirl. Could be a "full timeline" tab, where tweets, mentions and directs are shown as they come in (put them in the right temporal order when they arrive) with color-coded backgrounds. IMHO it's the best way to access information from Twitter.

**Comment by cezarsa** [comment]
I also think that'd be an awesome feature for Chromed Bird, and I'm working on this right now. It's not ready yet, but you can already check the unified_timeline branch.
I still have some doubts on the correct behavior for the unified timeline, mainly when scrolling down to fetch older tweets. I'll elaborate that further later today and ask for your option on this.

**Comment by juanfra684** [comment]
For me is better if CB show list1+list2+replies+DM without the timeline.

**Comment by pmbarros** [comment]
Customizable "home" tab, showing tweets from whatever set of sources that the user selects. Default could be either the timeline or an unified DM+@replies+normal tweets. Does this sound feasible?

**Comment by cezarsa** [comment]
If you check the current source you'll see that this feature is almost ready and already functional. It'd be awesome if you could download the source and install it as an unpacked extension just to give me your feedback about this feature, before publishing it.

When you check the options page, you'll notice that there's a new tab available to be selected as visible, it's called "Unified". Also there's a new column allowing you to select which timelines will compose the unified timeline. One thing that I still intend to add is the ability to have tweets differentiated by color depending on which timeline it comes from.

**Comment by pmbarros** [comment]
Running on the current source now. Scrolling down seems inconsistent: messages from the different sources don't seem to go back to the same time. Right now, it shows me regular tweets up to 6 hours ago; @replies up to a month ago, and all my DMs. Going down makes some more regular tweets show up way near the top and some @replies near the middle of the line.

Seems to me that the most consistent way to do this would be to request "N" messages from each source, and show only the most recent "M" of them initially. As the user scrolls down, "M" more messages appear. If the requested pool from one source is empty, request "N" more of that source so you will always have the most recent messages on your screen; or, better put, you can always be sure that there is no message that is more recent than any of those you have on the "unified" tab that isn't shown on that tab. Does that make sense to you?

**Comment by cezarsa** [comment]
You're right scrolling down is really crazy currently. I did understand your proposal and it seems the right way to do it, I'm going for it right now. Thanks!

**Comment by cezarsa** [comment]
Hey there pmbarros and every other available beta tester. :)
I've just pushed a new commit improving unified timeline consistency. Now I think we're on the right path.
So, are you available to test it again and give me your feedback?
Thanks a lot!

**Comment by juanfra684** [comment]
I like the unified timeline but need differents colors for each source.

**Comment by cezarsa** [comment]
Yeah, that's the next step :)

**Comment by pmbarros** [comment]
Another issue: you cannot delete a DM from the unified view. Also, it doesn't update when you post a tweet. Besides those two small issues, I've been using it all day long without a glitch.

**Comment by cezarsa** [comment]
Now it's all ready and working on master branch. I'll release it as a new version tomorrow as I still want to arrange some stuff. It'd be really nice if you could try it one last time. :) Thanks a lot!

**Comment by cezarsa** [comment]
Closing this issue as I'm about to publish this.

**Comment by jskeet** [comment]
Awesome - it's updated now. Sorry I wasn't able to beta test it, but thanks ever so much for the feature. Looks great!
