### ISSUE TITLE
Unexpected error "undefined"(timeout) updating tweets. Try again

### ISSUE THREAD

**Issue by yhager** [cezarsa/silver_bird#64]
No matter what I do - restart, re-install, reset prefs, incresing timeout - I keep getting this timeout error, and I see no tweets.

using v1.4.2, on Chrome 4.0.266.0_p33995 on Linux

**Comment by cezarsa** [comment]
Could you please try again in version 1.4.8?

**Comment by yhager** [comment]
Sorry - that was a typo - I am using v1.4.8.

**Comment by cezarsa** [comment]
Nope it wasn't a typo, I just released 1.4.8 about 7 hours ago. So, you're still getting the same error message?

**Comment by yhager** [comment]
ah! you jumped from 1.4.2 to 1.4.8 - that confused me.

Anyway, yes - same error on v1.4.8.

**Comment by oxyghene** [comment]
i'm using version 1.6.1 and i have the exact same problem. 
in the option i find this:
Rate Limit Reset: Wednesday, December 31, 1969 21:00:00
and nothing, absolutely nothing i do changes this. in my other pc it works just fine and the date in the Rate Limit Reset is normal, February 22, 2010.

i love this ad-on, but just can't solve this.

**Comment by oxyghene** [comment]
oh, and by the way, there's a window that pop up and says that this is probably because the date and time in the os is wrong, but it is not. neither is the date in the navigation history in the chrome itself

**Comment by yhager** [comment]
I moved to 1.6.1 and it's the same. If you can suggest a patch for debugging purposes, I can install it and report the results.

**Comment by cezarsa** [comment]
Hey guys, so we're probably talking about 2 different issues in here.

@oxyghene The options page show this incorrect reset date because you aren't logged in yet, and that's because there's a OAuth authentication failure in the login process. I have a workaround in the current source that will probably mitigate this problem but it wasn't published in any version yet, meanwhile you can either download the current source or you can review your system time settings, timezone settings and daylight saving time settings, as this is always the cause for this kind of problem.

@yhager Could you please paste me your "Twitter's API URL" and "OAuth Signature URL" settings? Also, please check if you can have access to these urls in your browser.

**Comment by yhager** [comment]
I have:
Twitter's API URL: http://twitter.com/
OAuth Signature URL: http://twitter.com/
OAuth Authorize URL: https://twitter.com/oauth/authorize?oauth_token=

I can access twitter.com, and trying to access the oauth url, I get a twitter page with: 
"Woah there!
This page is no longer valid. It looks like someone already used the token information you provided. Please return to the site that sent you to this page and try again … it was probably an honest mistake."

**Comment by cezarsa** [comment]
Weird, could you access the extensions page, click the background.html link and check if there's any error being shown on the console?

**Comment by yhager** [comment]
nope, no error. 
In the 'Logs' tab I get:
XHR finished loading: "http://twitter.com/account.rate_limit_status.json?oauth...[snip]
and clicking that I see the twitter json response: {"remaining_hits":150,"hourly_limit":150 [snip]}

**Comment by oxyghene** [comment]
hey,

first, thanx for answering so fast.

second, i already reviewed my system time settings, timezone settings and daylight saving time settings and it's just fine. everything is correct. but the problem persists.

it still won't log and the date reset limit continues to show an absurd date (December, 1969). that is exaclty why i tried to contact you here. i checked foruns and follow the advice of the window that opens; every date, time and adjustments of the sort are just OK. i even went to my twitter account and fixed the time settings there. but nothing worked.

**Comment by cezarsa** [comment]
@oxyghene Could you please try downloading the current source[1], installing it as an unpacked extension and testing if it works? I've been working on some improvements to OAuth authentication that might fix this.
[1] http://github.com/cezarsa/chromed_bird/zipball/master

**Comment by cezarsa** [comment]
@yhager That's odd, there should have been many other XHR requests for each timeline. Something seems to be preventing them. 
To be clear, you are able to authenticate using OAuth, right? And after that when you open the popup you get this "Unexpected error "undefined"(timeout) updating tweets." error, right?

**Comment by oxyghene** [comment]
@cezarsa

tried but got the same results. it still won't log and the reset date remains dec, 1969. when trying again, the same window pops up telling me to check my date settings.

**Comment by yhager** [comment]
I see three XHR's in the log when clicking 'background.html':
- XHR finished loading: "chrome-extension:..
- XHR finished loading: "http://twitter.com/account/rate_limit_status.json?oauth_consumer_key=...
- XHR finished loading: "http://api.longurl.org/v2/services?format=json".

> To be clear, you are able to authenticate using OAuth, right

How do I check that?

**Comment by cezarsa** [comment]
First time you click Chromed Bird's icon after opening Chrome, does it open a new tab asking you to allow it to access your Twitter account?

**Comment by cezarsa** [comment]
@oxyghene Now I'm out of clues, I'm working on some authentication improvements that might help. I'll probably release a new version by Sunday, then I'll ask you to test it again.

**Comment by yhager** [comment]
Wow.. now this is embarrassing. 
I am quite certain I gave it access, but it was long time ago. I didn't see the bird in my twitter 'connections' tab, so after receiving this error message, I clicked 'logout' and clicked the bird again. It asked for access, and suddenly everything is working again.

I think the error message should give a clue about this case, of at least the faq. I hope you don't feel you wasted your time - even trivial things seems unclear to users sometime and need to be documented.

**Comment by cezarsa** [comment]
@yhager Nice to hear it's finally working again. You're right, I probably need some way to detect revoked or expired oauth tokens to alert user properly. I'll make sure to include such detections in the next version. Also thanks for your patience tracking this down.

**Comment by yhager** [comment]
Thank you for your continued support on this!
