### ISSUE TITLE
Lists Dropdown Behavior

### ISSUE THREAD

**Issue by mtmccurdy** [cezarsa/silver_bird#66]
Hey --

Not quite the same bug I was dealing with earlier (no error message), but:

Clicking on the dropdown menu for lists instantly clears the timeline until you click on a specific list or click on the 'Home' tab.  I believe that the behavior should act as other dropdowns do, namely that nothing at all would change until a specific list is chosen.  I should be able to have my home timeline open, click the lists dropdown and have nothing change, and then click out of the dropdown without making a selection and still see my home timeline.  Additionally, I should be able to click the dropdown and have nothing change and then select a list -- only then should the timeline change in any way.

Clicking on the lists dropdown and then not making a specific selection still causes no timeline to appear when you reopen the Chromed Bird extension area.  

Additionally, clicking the name of a list and then clicking the 'Home' tab still leaves the name of the previously opened list in the dropdown as active.  It should be reset to '-select list-' when the home tab is clicked.

If any of this behavior is not abnormal, and intended, then please ignore this.

Great extension!

-M

p.s. - latest mac dev on mac os 10.6

**Comment by cezarsa** [comment]
Okay, since you're a Mac user and I'm not, you most surely know a lot more about UI usability than I do. :) Just kidding, but you've a good point in the way the dropdown should work. I'm going to follow your suggestions soon.
Thanks a lot for your feedback.

**Comment by mtmccurdy** [comment]
Haha, thanks.  I love this extension -- it makes twitter so much more usable.
