### ISSUE TITLE
Show Chromed Bird in a independent window

### ISSUE THREAD

**Issue by juanfra684** [cezarsa/silver_bird#69]
When I clicked in the Chromed Bird icon, it should to permit to show the client in a independent window. Of course this should to be seleccionable in options. ie: "Traditional popup" or "Independent window".

This behavior will permit to use Chromed Bird like a traditional twitter client while the browser has the window minimized and other applications has the window maximized. Example http://is.gd/66rlJ .

Apologies for my english and thanks for your work.

**Comment by cezarsa** [comment]
It might be quite easy to make Chromed Bird work in a full tab, but if I understand it correctly that's not your proposal, right?
You want Chromed Bird to float on the right of any open page, is that it? If that's what you're proposing, it's kinda not possible right now. There's a Chromium feature request that might help it though: http://code.google.com/p/chromium/issues/detail?id=30688
You might want to star this issue.

**Comment by juanfra684** [comment]
My proposal is that Chromed Bird works in a full tab :) (in a popup without toolbars is better for me)

**Comment by cezarsa** [comment]
Okay, right now if you just point your browser to chrome-extension://encaiiljifbdbjlphpgpiimidegddhic/popup.html it should work. However there'll be some issues when clicking on links, but that could be easily fixed. Is that what you want?

**Comment by juanfra684** [comment]
Yes, "google-chrome --app=chrome-extension://encaiiljifbdbjlphpgpiimidegddhic/popup.html" is perfect for me. But I need that the extension use all window, now only use the horizontal space.

Thanks.

**Comment by cezarsa** [comment]
You're right, there's this one other issue indeed. I'll take a look at it along with fixing link targets.

**Comment by cezarsa** [comment]
Expanding timeline if we're in an independent window. Closed by 5a442a46235b710b7e4f811799faec19d9374a26
