### ISSUE TITLE
Click the link do not close the popup window

### ISSUE THREAD

**Issue by spitfire2** [cezarsa/silver_bird#7]
Click the link do not close the popup window

**Comment by cezarsa** [comment]
Yeah, I agree that sometimes it's really annoying. I'm thinking about trying to mimic Chromes's behavior. I'll try to do something like if you click the link with the left mouse button, it will behave just like it does today, closing the popup and switching the focus to the new popup. But, if you click the link with the middle mouse button or Ctrl-click the link, it will open the new tab on background, keeping the popup open. I think that's possible.
If everything goes well you can expect this fix to be on the new version probably next Sunday.

**Comment by cezarsa** [comment]
Ctrl-click and middle click open links without closing the popup. Closed by 40170595a5ec7ef0a585ab6da0ab0ac130a7f45c
