### ISSUE TITLE
Link timestamp to status page (as on twitter.com)

### ISSUE THREAD

**Issue by tbroyer** [cezarsa/silver_bird#70]
One feature I like on twitter.com is that a tweet timestamp is linked to the individual status page (just like the "in reply to" links that Chromed Bird already supports), that way I can easily "share" a tweet via IM, mail or a link in a web page.

In Chromed Bird I'm forced to open the tweet author timeline on twitter.com (or my timeline, though there's no direct link in Chromed Bird, so opening the tweet author timeline is easier) and find the tweet back so I can have a link to its individual page.

Looks like it'd be one-liner in Chromed Bird. Tell me if you want me to provide a patch.

**Comment by cezarsa** [comment]
Linking timestamp to status page. Closed by 53f1b620b40e2226ccc2c34e422736e6ca08d919
