### ISSUE TITLE
Whisper theme's warning message has a transparent background

### ISSUE THREAD

**Issue by hyperlink** [cezarsa/silver_bird#73]
Switch to the Whisper theme and get the API warning.

**Comment by cezarsa** [comment]
Awesome. Thank you again for for the patch hyperlink. I've just pushed it.
Next time, to save you from extra work, it's okay to just paste the patch in a Gist or something and comment here. But it's okay anyway. :)

Closed by 01c262ad4b9561957f74f1cde92bde84657101aa

**Comment by cezarsa** [comment]
Forgot to close.

**Comment by hyperlink** [comment]
Ah, didn't want to risk messing up the formating of the patch file. I'll paste it next time. :)
