### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by livin52** [cezarsa/silver_bird#74]
More info: http://code.google.com/chrome/extensions/trunk/i18n.html

**Comment by cezarsa** [comment]
Nice, that's going to be a long time goal. :) The main problem right now is that if we start working on that direction we're gonna break compatibility with the Beta channel. I think it's okay to start a new branch to work on i18n though, that's probably what I'm going to do as soon as I have more time.

**Comment by livin52** [comment]
I can help with the Spanish translation.

**Comment by cezarsa** [comment]
Oops shame on me, I just noticed that i18n is already available on the Beta channel. So I guess it's already about time to start working on this.

**Comment by livin52** [comment]
When you get the English messages file done, tell me and I'll make the Spanish one... ;)

**Comment by Ikke** [comment]
I've made a begin with i18n and sent a pull request to cezarsa.

**Comment by nagos** [comment]
I can help with Russian translation.

**Comment by cezarsa** [comment]
Thank you a lot Ikke, I've just pushed your commits.
Are you willing to continue on this or should I take it from here? n/p either way, I'm just asking to avoid we both working on the same thing.
Thanks again.

**Comment by skarcha** [comment]
I think that this issue can be closed. I did the internationalization a few weeks ago and cezarsa pushed it.

**Comment by cezarsa** [comment]
Issues clean-up at last!
