### ISSUE TITLE
Some texts are undefined

### ISSUE THREAD

**Issue by konstantinov** [cezarsa/silver_bird#78]
In 1.4.9 version http://img18.yfrog.com/i/71784851.png/

**Comment by anarchivist** [comment]
I'm seeing this in 1.4.9 as well on Chrome 4.0.249.43.

**Comment by konstantinov** [comment]
anarchivist, yeah, i have same version of chrome

**Comment by cezarsa** [comment]
Really sorry for that guys, I really shouldn't have published 1.4.9 yesterday as it wasn't quite ready yet.
I just fixed that mess publishing 1.4.9.1 a few minutes ago. It should work flawlessly again. You may click the "Update extensions now" button to hush the auto-update process.

**Comment by cezarsa** [comment]
Closed by quickfix branch

**Comment by konstantinov** [comment]
thnx, work nice now
