### ISSUE TITLE
Area containing tweets expands in width on loading older tweets

### ISSUE THREAD

**Issue by anarchivist** [cezarsa/silver_bird#79]
I'm seeing this on Chrome 4.0.249.43 on Linux and Chromed Bird 1.4.9.1 (was seeing this on 1.4.8 and 1.4.9 as well I believe). If I click on the icon to see my tweets, it's fine, but on occasion, the area containing the tweets expands if I scroll down and Chromed Bird loads older tweets.

**Comment by anarchivist** [comment]
Screenshots:
http://picpaste.com/chromedbird1.png
http://picpaste.com/chromedbird2.png

**Comment by anarchivist** [comment]
Also: It doesn't happen every time an older set of tweets is loaded - it appears to possibly be related of tweets of a certain length.

Disabling and reenabling the extension or logging out and getting new OAuth credentials resets it to the proper width.

**Comment by cezarsa** [comment]
Yeah, that's a side effect of handling overflow in tabs. I really need to find a way to solve this. I found out that this problem is usually caused by long urls as they don't wrap around anymore, maybe just shortening them before displaying would solve the problem.
