### ISSUE TITLE
Direct Messages issue v0.4

### ISSUE THREAD

**Issue by Mysto-zz** [cezarsa/silver_bird#8]
Hi Ho :P

Great Addon for Chrome, made me switch from Firefox this time! :D

One issue i found just now was that every time i write a Direct Message, Chromed Bird sends it but the addon itself crashes in some way!

The loading icon is in an never-ending loop, my latest Tweets wont show up!

My solution to get normal functions is disable/enable extension!

I am not sure if that happened in earlier versions but in my case it happens!

Lates Chrome Dev version and lates Chromed Bird Version v.04!

Hope i could help!

**Comment by cezarsa** [comment]
Correctly handling updates after sending a tweet that won't show at home timeline. Closed by 1478ea397396b1499a6b82c77c1003a22555b8ff

**Comment by cezarsa** [comment]
Thanks for reporting Mysto, it's now fixed on head. I'll wait until the weekend to release this fix as a new version. I hope I'll have enough time to finish tabs support until then.
