### ISSUE TITLE
Not updating Timeline Bug

### ISSUE THREAD

**Issue by chicocvenancio** [cezarsa/silver_bird#82]
My Chromed bird stopped updating the timeline. Direct Messages still update, but not the main timeline.I use windows XP, Chrome dev 4.0.295.0, and chromed bird is updated to version 1..4.9.

**Comment by cezarsa** [comment]
Hey there, the latest version is 1.4.9.1, version 1.4.9 had a serious bug that really caused timelines to stop updating.
Could you update the extension and check if this issue still happens? (You can hush the update process by clicking the "Update extensions now" button in the extensions page). Thanks.

**Comment by cezarsa** [comment]
As I got no response from this I'm closing this issue.
