### ISSUE TITLE
How to attach the patch?

### ISSUE THREAD

**Issue by edwardyoon** [cezarsa/silver_bird#85]
I'd like to contribute some patches for this project.

BTW, I'm newbie in github infra-. Does anyone knows about it?

**Comment by cezarsa** [comment]
Hey there. You could either fork the repository and send me a pull request or use git format-patch and paste it in a Gist: http://gist.github.com/

**Comment by edwardyoon** [comment]
Thanks.

**Comment by edwardyoon** [comment]
I just closed this.

**Comment by cezarsa** [comment]
Closing now
