### ISSUE TITLE
Error 203: You must be authenticated to access shorten

### ISSUE THREAD

**Issue by TheGift73** [cezarsa/silver_bird#86]
Really like this extension. The one issue that I am having is the following error message when using bit.ly to shorten a URL:-
Error 203: You must be authenticated to access shorten
I have filled out my API Login correctly and also triple checked my API Code is correct.
Any ideas?
Apart from that I'm really pleased to have found this extension

**Comment by cezarsa** [comment]
Hmm that's odd, I can't get a repro on this. It does show this error when either API key or login are incorrect, but when them both are correct it works fine.
Have you tried reseting your bit.ly API key?

**Comment by TheGift73** [comment]
Figured it out. 
My username on Twitter is TheGift73 (please note the capital T and G)
On your Bit.ly account when it generates your API Login and API Code, it only uses lower case letters for the API Login. This means that in the options settings of Chrome Bird add-on  (in Chrome in my case) you must enter the lower-case version of your username, not how it actually is on Twitter.

**Comment by cezarsa** [comment]
Cleaning up issues list.
