### ISSUE TITLE
On "Darkness" theme, remaining number of characters doesn't appear

### ISSUE THREAD

**Issue by pmbarros** [cezarsa/silver_bird#87]
On the new theme, the number of characters remaining is printed in black over a black background, making it invisible unless you manually select it.

**Comment by cezarsa** [comment]
hyperlink have already fixed this one: e4444f2aed009e01b83dc38d1d7eabc3f2b78869
It'll be available in the next update (by the weekend)

**Comment by cezarsa** [comment]
Cleaning up issues, this fix is already in.
