### ISSUE TITLE
Color tweets depending on the list the tweeter is in

### ISSUE THREAD

**Issue by dominikmayer** [cezarsa/silver_bird#89]

**Comment by pmbarros** [comment]
That would open the way for Issue 63, as you could easily see the difference between a regular tweet, a mention, a DM and a tweet from your currently selected list even if they are all shown on the same page.

**Comment by cezarsa** [comment]
Yeah, that's totally related to #63. Actually I'm working on this right now, unified timeline isn't ready yet, but if you want you can check the work in progress in the unified_timeline branch.

**Comment by cezarsa** [comment]
Closed by 25335370b64fef1104ae53c8e1d46bf90acdb3b2
