### ISSUE TITLE
Authenticate using OAuth protocol

### ISSUE THREAD

**Issue by cezarsa** [cezarsa/silver_bird#9]
Currently we rely on Basic Auth, despite the fact that it works pretty well and that it's relatively secure through HTTPS, there are still security concerns on the client side because we're storing user authentication information inside Chrome's localStorage. Besides that, all tweets coming from Chromed Bird are shown by Twitter as "from API".

To improve security and correctly show tweets as "from Chromed Bird" we need change the authentication mechanism and use the OAuth protocol.
I'll surely work on this anytime soon, but if someone in the wild wants to give me a hand on this I'd greatly appreciate. :)

**Comment by cezarsa** [comment]
Authenticating using OAuth protocol. Closed by 2348180cca907cad901bd8241e94d42d2768a0a5

**Comment by aardvark** [comment]
1.2.0 still Unable to pass OAuth under Iron 4.0.227.0 (30207).  Freeze on "Please wait, authorizing Chromed Bird..."

**Comment by cezarsa** [comment]
Damn, I intended to support this, I even added the ability to manually enter the PIN code, but I forgot that I hide the PIN number while trying to communicate with the extension.
I'll fix this for the next version, meanwhile, if you can quickly grab the PIN number before it vanishes from the page, you can type it into Chromed Bird, and it should complete the authentication properly.

**Comment by aardvark** [comment]
Quickly grab worked. Had to find pin in cache pages, but it work for now.

**Comment by cezarsa** [comment]
Cool, I promise I'll fix this for the next version. :)
