### ISSUE TITLE
Support for identi.ca

### ISSUE THREAD

**Issue by felipec** [cezarsa/silver_bird#90]
Identi.ca is a another microbloging service, but it's open. It has many more options, including relaying to twitter.

**Comment by cezarsa** [comment]
Seamlessly supporting identi.ca microblogging service. Just switch the microblogging service in the options page. Closed by a73a0834dc886de5d58b7d2663db48842453fbac and Closed by a73a0834dc886de5d58b7d2663db48842453fbac
