### ISSUE TITLE
Add additional url shortener urli.nl

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#95]
Please add urli.nl as additional url shortener.

http://urli.nl/api.php?&format=simple&action=shorturl&url=http://www.orkut.com
http://urli.nl/api.php?&format=xml&action=shorturl&url=http://www.orkut.com
http://urli.nl/api.php?&format=json&action=shorturl&url=http://www.orkut.com

Default
http://urli.nl/api.php?&action=shorturl&url=http://www.orkut.com

Cheers,
Rudolf Pietersma

**Comment by cezarsa** [comment]
Adding URLi.nl shortener. Closed by 6a2ae5447c21704818b9b71195bbfc3cc9346d6a
