### ISSUE TITLE
Add additional url shortener urli.nl

### ISSUE THREAD

**Issue by ghost** [cezarsa/silver_bird#96]
Can you add urli.nl as additional url shortener?

http://urli.nl/api.php?&format=simple&action=shorturl&url=http://www.yourlongurlthatneedstobeshortened.com
http://urli.nl/api.php?&format=xml&action=shorturl&url=http://www.yourlongurlthatneedstobeshortened.com
http://urli.nl/api.php?&format=json&action=shorturl&url=http://www.yourlongurlthatneedstobeshortened.com

**Comment by ghost** [comment]
Sorry I thought my issue was not added to the list, because I had an internet connection error. Just saw that it was issue 95.

**Comment by cezarsa** [comment]
Yeah, it's already in and should be available once I publish a new version latter today.

**Comment by ghost** [comment]
Great!
When will the new version be published?

Rudolf.

**Comment by cezarsa** [comment]
It's out now, just wait for autoupdate to kick in.

**Comment by ghost** [comment]
Great, tnx a lot!
